### ISSUE TITLE
File writing fails for some filenames

### ISSUE THREAD

**Issue by valschmidt** [PyTables/PyTables#707] opened 2018-09-01 03:57 UTC
I'm using pytables via pandas v 0.22.0, specifically the to_hdf() and read_hdf() methods, and I'm seeing some very odd behavior, in which my ability to write a DataFrame to an hdf file or read that file back is dependent on my chosen file name convention. Underbars and any modification of the suffix produces errors. Oddly my ability to write files is different from a script vs interactively from ipython (both using the same version of pandas). Here are some examples:

Within a script I can write a DataFrame with the following:
`df.to_hdf('data_parsed_GGA.h5',key='/GGA',format='table')`

But within ipython, this file is unreadable with 
`data = pd.read_hdf('data_parsed_GGA.h5')`

```
...
/Users/vschmidt/anaconda/lib/python2.7/site-packages/pandas/io/pytables.pyc in open(self, mode, **kwargs)
    610             # is not part of IOError, make it one
    611             if self._mode == 'r' and 'Unable to open/create file' in str(e):
--> 612                 raise IOError(str(e))
    613             raise
    614 

IOError: HDF5 error back trace

  File "H5F.c", line 604, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1087, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 277, in H5F_super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data_parsed_GGA.h5'
```

Oddly, within ipython I cannot write an identical DataFrame by executing the same line above. I get the following error :
```
...
/Users/vschmidt/anaconda/lib/python2.7/site-packages/tables/file.pyc in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    782 
    783         # Now, it is time to initialize the File extension
--> 784         self._g_new(filename, mode, **params)
    785 
    786         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 604, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1087, in H5F_open
    unable to read superblock
  File "H5Fsuper.c", line 277, in H5F_super_read
    file signature not found

End of HDF5 error back trace

Unable to open/create file 'data_parsed_GGA.h5'
```

A similar error occurs if I try to write the data file without a suffix of `.h5`. (For example, I wanted to use `.ph5` to indicate hdf5 files written by pandas/pytables. )

However, within ipython, if I remove the underbars from the file name (e.g. dataparsedGGA.h5) then the file is written without error. 

I realize these errors are generated in the HDF5 library. [Why HDF5 cares about the format of the filename is wholly baffling and ludicrous.] But perhaps pytables could shield python users from this, by catching incompatible filenames and raising a meaningful error that guides the programmer to a compatible choice.

**Comment by FrancescAlted** [comment] 2019-03-12 10:02
This is really strange and should not be happening.  Can you send a minimal script reproducing this?

**Comment by avalentino** [comment] 2021-12-27 16:02
I'm not able to reproduce, closing.
@valschmidt please feel free to re-open if you have a simple code example to reproduce it.

**Closed by avalentino** 2021-12-27 16:02 UTC
Labels: defect, good first issues
