### ISSUE TITLE
PyTables 3.3.0 bug with Pandas DataFrame

### ISSUE THREAD

**Issue by kylekeppler** [PyTables/PyTables#598] opened 2017-01-20 19:00 UTC
In python 2.7, pandas 0.19.2, pytables 3.3.0 (from anaconda), I am unable to create hdf5 files with pandas `HDFStore`:

Example from http://pandas.pydata.org/pandas-docs/stable/io.html#id2:

```python
df_tl = pd.DataFrame(dict(A=list(range(5)), B=list(range(5))))

df_tl.to_hdf('store_tl.h5','table',append=True)
```
Result:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-7024f813600a> in <module>()
      1 df_tl = pd.DataFrame(dict(A=list(range(5)), B=list(range(5))))
      2 
----> 3 df_tl.to_hdf('store_tl.h5','table',append=True)

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\core\generic.pyc in to_hdf(self, path_or_buf, key, **kwargs)
   1136 
   1137         from pandas.io import pytables
-> 1138         return pytables.to_hdf(path_or_buf, key, self, **kwargs)
   1139 
   1140     def to_msgpack(self, path_or_buf=None, encoding='utf-8', **kwargs):

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    268         with HDFStore(path_or_buf, mode=mode, complevel=complevel,
    269                       complib=complib) as store:
--> 270             f(store)
    271     else:
    272         f(path_or_buf)

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in <lambda>(store)
    260 
    261     if append:
--> 262         f = lambda store: store.append(key, value, **kwargs)
    263     else:
    264         f = lambda store: store.put(key, value, **kwargs)

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in append(self, key, value, format, append, columns, dropna, **kwargs)
    968         kwargs = self._validate_format(format, kwargs)
    969         self._write_to_group(key, value, append=append, dropna=dropna,
--> 970                              **kwargs)
    971 
    972     def append_to_multiple(self, d, value, selector, data_columns=None,

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in _write_to_group(self, key, value, format, index, append, complib, encoding, **kwargs)
   1313 
   1314         # write the object
-> 1315         s.write(obj=value, append=append, complib=complib, **kwargs)
   1316 
   1317         if s.is_table and index:

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   3850         self.create_axes(axes=axes, obj=obj, validate=append,
   3851                          min_itemsize=min_itemsize,
-> 3852                          **kwargs)
   3853 
   3854         for a in self.axes:

C:\Anaconda3\envs\py106_py27_2\lib\site-packages\pandas\io\pytables.pyc in create_axes(self, axes, obj, validate, nan_rep, data_columns, min_itemsize, **kwargs)
   3522                 self.values_axes.append(col)
   3523             except (NotImplementedError, ValueError, TypeError) as e:
-> 3524                 raise e
   3525             except Exception as detail:
   3526                 raise Exception(

TypeError: shape must be an integer or sequence: 2L
```

The exception the pandas is re-raising comes from [`atom.py` line 128-131:](https://github.com/PyTables/PyTables/blob/v3.3.0/tables/atom.py#L128)

```python
    try:
        shape = tuple(shape)
    except TypeError:
        raise TypeError("shape must be an integer or sequence: %r"
```

So clearly the problem is the code attemping to perform `tuple(2L)`.  I have no idea why pandas is using a long here, but that has not changed in pandas and this works with pytables 3.2.2.

Diffing atom.py we can see a change was made that seems like is causing this:

[atom.py line 123 pytables 3.3.0](https://github.com/PyTables/PyTables/blob/v3.3.0/tables/atom.py#L123):
```python
    if isinstance(shape, (int, numpy.integer, int)):
```

[atom.py line 118 pytables 3.2.2](https://github.com/PyTables/PyTables/blob/v.3.2.2/tables/atom.py#L118):
```python
    if isinstance(shape, (int, numpy.integer, long)):
```

[atom.py line 119 pytables 3.2.3.1](https://github.com/PyTables/PyTables/blob/v.3.2.3.1/tables/atom.py#L119):
```python
    if isinstance(shape, (int, numpy.integer, long)):
```

Seems like the long -> int change is the cause.

**Comment by tomkooij** [comment] 2017-01-20 19:10
Thanks for reporting. This is caused by d4f710a (single codebase py2 and 3 support) that was merged into the 3.3.0 release.

There is no `long` in python 3. The code in `atom.py`should be:
```
if isinstance(shape, (numpy.integer, six.integer_types)):
```

I'll push a fix.

**Comment by andreabedini** [comment] 2017-01-21 07:49
that line must have slipped through my bad.

**Closed** 2017-02-20 12:48 UTC
Labels: defect

**Comment by eskemojoe007** [comment] 2017-02-27 14:22
I am still having this issue with python 2.7.13, pandas 0.19.2, and pytables 3.3.0

**Comment by tomkooij** [comment] 2017-02-27 16:34
@eskemojoe007 This is fixed in the `develop` branch, which is not released yet.

You can install Pytables from this repo your self. 

Or fetch the (unofficial) wheels from appveyor (windows):
https://ci.appveyor.com/project/PyTablesBot/pytables/build/job/erf2j7u0is5jkax1/artifacts
(other windows wheels in that same build)

I don't think this is possible for the Travis (Linux) builds.
