### ISSUE TITLE
test() failed after installation

### ISSUE THREAD

**Issue by wsun88** [PyTables/PyTables#433] opened 2015-04-15 14:56 UTC
System Info
PyTables version:  3.1.1
HDF5 version:      1.8.14
NumPy version:     1.9.2
Numexpr version:   2.3.1 (not using Intel's VML/MKL)
Zlib version:      1.2.8 (in Python interpreter)
LZO version:       2.06 (Aug 12 2011)
BZIP2 version:     1.0.6 (6-Sept-2010)
Blosc version:     1.3.5 (2014-03-22)
Blosc compressors: ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib']
Cython version:    0.22
Python version:    2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
Platform:          Linux-3.13.0-48-generic-x86_64-with-debian-jessie-sid
Byte-ordering:     little
Detected cores:    1
Default encoding:  ascii
Default locale:    (en_US, UTF-8)

ERRORS:
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................./home/ubuntu/anaconda/lib/python2.7/site-packages/tables/path.py:100: NaturalNameWarning: object name is not a valid Python identifier: 'test_filenode.dat'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though
  NaturalNameWarning)
..
======================================================================
ERROR: test05b_modifyColumns (tables.tests.test_nestedtypes.WriteNoReopen)
Modifying two nested columns (modify_columns).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/tests/common.py", line 144, in newmethod
    return oldmethod(self, *args, **kwargs)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/tests/test_nestedtypes.py", line 527, in test05b_modifyColumns
    dtype=raCols.dtype)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/records.py", line 518, in fromarrays
    arrayList = [sb.asarray(x) for x in arrayList]
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 3549, in __iter__
    out=buf_slice)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 1975, in read
    arr = self._read(start, stop, step, field, out)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 1879, in _read
    bytes_required))
ValueError: output array size invalid, got 8 bytes, need 16 bytes

======================================================================
ERROR: test05b_modifyColumns (tables.tests.test_nestedtypes.WriteReopen)
Modifying two nested columns (modify_columns).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/tests/common.py", line 144, in newmethod
    return oldmethod(self, *args, **kwargs)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/tests/test_nestedtypes.py", line 527, in test05b_modifyColumns
    dtype=raCols.dtype)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/records.py", line 518, in fromarrays
    arrayList = [sb.asarray(x) for x in arrayList]
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py", line 462, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 3549, in __iter__
    out=buf_slice)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 1975, in read
    arr = self._read(start, stop, step, field, out)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 1879, in _read
    bytes_required))
ValueError: output array size invalid, got 8 bytes, need 16 bytes

----------------------------------------------------------------------
Ran 5659 tests in 218.580s

FAILED (errors=2)

**Comment by FrancescAlted** [comment] 2015-04-15 15:05
We are in the process of releasing 3.2.0.  Can you try with this branch:

https://github.com/PyTables/PyTables/commits/release-3.2.0

and report back how it goes?

**Comment by FrancescAlted** [comment] 2015-04-18 12:29
I cannot reproduce the issue in any tested platform so far, so closing.

**Closed by FrancescAlted** 2015-04-18 12:29 UTC
