### ISSUE TITLE
Problem with hdf5.dll

### ISSUE THREAD

**Issue by ulfllorenz** [PyTables/PyTables#952] opened 2022-04-29 14:53 UTC
I have a Windows application that uses hdf5.dll for internal purposes, but also has an add-in mechanism that allows the execution of add-ins through Python in the same process. One of the add-ins, in turn, pulls in pytables.

If I use pytables version 3.6.1, Pytables crashes, because it uses the application's hdf5.dll. As far as I can read the code, upgrading to 3.7.0 should solve this because the __init__.py explicitly loads namespaced libraries (hdf5-something.dll) as dependencies. Is this understanding correct?

What puzzles me here is that the wheel from the official pip repository still has a hdf5.dll in the package directory. Is this a leftover artefact from building, or do you still require this dll?

**Comment by avalentino** [comment] 2022-04-29 15:47
@ulfllorenz thanks for reporting.
Indeed it seems that there is something weird in the wheels for windows.
If I remember correctly after the lates release there was some cleanup in that area but things could still be not perfectly fine.
Do you mind to give a try to the current master?
Wheels should still be available as artifacts of the CI system.

**Comment by Chronial** [comment] 2022-04-29 19:16
I had a look at the python3.9 wheel generated by https://github.com/PyTables/PyTables/actions/runs/2043936401 and it looks better. The superfluous copy of the hdf5.dll seems to be gone.

**Comment by avalentino** [comment] 2022-04-30 06:01
Thanks @Chronial for the quick feedback

**Comment by avalentino** [comment] 2022-05-07 08:50
OK I think that the issue is fixed in the current master.
@ulfllorenz please reopen if you still have problems with the latest git version

**Closed by avalentino** 2022-05-07 08:50 UTC
Labels: windows, wheel, help wanted
