### ISSUE TITLE
Memory leak when using compression

### ISSUE THREAD

**Issue by bertrandhaut** [PyTables/PyTables#546] opened 2016-05-04 14:00 UTC
Dear, 

I'm having a large application where I populate an HDF5 file with a series of tables. This application ends up in a MemoryError exception.

I've noticed a strange memory behavior reproduced here below:

# Test 1

	import uuid
	import numpy as np
	import tables
	import psutil
	import os
	import gc

	n = 1000

	def print_memory(mess=None):
		p = psutil.Process(os.getpid())
		m = p.memory_info()
		print("%-10.10s cur_mem->%.2f (MB)" % (mess, m.rss / 1000000.0))

	def add_a_element(store):
		data=np.random.rand(n, n)
		id = 'a' + str(uuid.uuid1()).replace('-', '')

		atom = tables.Atom.from_dtype(data.dtype)
		filters = tables.Filters(complib=None, complevel=1)
		ds = store.createCArray(store.root, id, atom, data.shape, filters=filters)
		ds[:] = data
		del data
		gc.collect()

	print(gc.collect())
	print_memory('start')

	store = tables.openFile('mystore2.hdf', mode='w')

	for i in range(10):
		add_a_element(store)
		gc.collect()
		print_memory('adding')

	store.close()
	gc.collect()
	print_memory('store_closed')

with as result:

 0
 start      cur_mem->61.95 (MB)
 adding     cur_mem->67.10 (MB)
 adding     cur_mem->69.55 (MB)
 adding     cur_mem->72.13 (MB)
 adding     cur_mem->74.63 (MB)
 adding     cur_mem->77.15 (MB)
 adding     cur_mem->79.66 (MB)
 adding     cur_mem->82.24 (MB)
 adding     cur_mem->84.78 (MB)
 adding     cur_mem->87.20 (MB)
 adding     cur_mem->89.81 (MB)
 store_clos cur_mem->67.04 (MB)

Why do we have this memory increase up to the point where the store is closed ?

# Test 2

The following code is more or less the same as the first one except that we use pandas object.

	import uuid

	import numpy as np

	import pandas as pd
	import tables

	import psutil
	import os
	import gc

	n = 1000

	def print_memory(mess=None):
		p = psutil.Process(os.getpid())
		m = p.memory_info()
		print("%-10.10s cur_mem->%.2f (MB)" % (mess, m.rss / 1000000.0))

	def add_a_element(store):
		df = pd.DataFrame(data=np.random.rand(n, n))
		id = 'a'+str(uuid.uuid1()).replace('-', '')
		store.put(id, df)
		del df
		gc.collect()

	print(gc.collect())
	print_memory('start')

	#creating store
	store = pd.HDFStore('mystore.hdf', mode='w', complib='zlib', complevel=1)
	# store = pd.HDFStore('mystore.hdf', mode='w')

	for i in range(10):
		add_a_element(store)
		gc.collect()
		print_memory('adding')

	store.close()
	gc.collect()
	print_memory('store_closed')

It leads to the same results:

0
start      cur_mem->61.86 (MB)
adding     cur_mem->67.05 (MB)
adding     cur_mem->69.63 (MB)
adding     cur_mem->72.15 (MB)
adding     cur_mem->74.66 (MB)
adding     cur_mem->77.16 (MB)
adding     cur_mem->79.70 (MB)
adding     cur_mem->82.26 (MB)
adding     cur_mem->84.80 (MB)
adding     cur_mem->87.27 (MB)
adding     cur_mem->89.78 (MB)
store_clos cur_mem->66.91 (MB)

However, if we remove the compression "complib=None", then the results looks good:

0
start      cur_mem->61.99 (MB)
adding     cur_mem->63.45 (MB)
adding     cur_mem->63.57 (MB)
adding     cur_mem->63.73 (MB)
adding     cur_mem->63.80 (MB)
adding     cur_mem->63.96 (MB)
adding     cur_mem->64.16 (MB)
adding     cur_mem->64.26 (MB)
adding     cur_mem->64.37 (MB)
adding     cur_mem->64.50 (MB)
adding     cur_mem->64.72 (MB)
store_clos cur_mem->64.78 (MB)

Note that in Test1, adding/removing the compression does not change anything.

Using pytables 3.2.2, Windows 64 bits, python 3.5.1 (anaconda distribution). Same issue on Linux.

**Comment by FrancescAlted** [comment] 2016-05-04 14:49
Umm, `tables.openFile()` is for PyTables 2 and older.  PyTables 3, tables.open_file() should be used instead.  Please double check which PyTables are you using via: `python -c"import tables; tables.print_versions()"`.

**Comment by jennolsen84** [comment] 2016-05-05 00:36
Does compression work for you?  I thought it was broken in pytables, and no one else noticed (so perhaps people aren't catching it or don't use it)

https://github.com/PyTables/PyTables/issues/461

**Comment by bertrandhaut** [comment] 2016-05-05 10:23
I've (currently) no more access to the computer used to made this test.

On my personnal computer, here are results of print_versions()

In [2]: tables.print_versions()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.2
HDF5 version:        1.8.15-patch1
NumPy version:       1.10.4
Numexpr version:     2.5.2 (using VML/MKL 11.3.1)
Zlib version:        1.2.8 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Cython version:      0.23.4
Python version:      3.4.4 |Anaconda 2.4.1 (64-bit)| (default, Feb 16 2016, 09:54:04) [MSC v.1600 64 bit (AMD64)]
Platform:            Windows-10-10.0.10586
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: mbcs
Default locale:      (fr_FR, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

(with this version, I received message about depracated openFile and createCArray() function).

Nevertheless the results are the same regarding the increased memory usage

In [9]:
Do you really want to exit ([y]/n)?
Closing remaining open files:mystore2.hdf...done

d:\tmp>python test.py
0
start      cur_mem->31.56 (MB)
adding     cur_mem->36.91 (MB)
adding     cur_mem->39.42 (MB)
adding     cur_mem->41.68 (MB)
adding     cur_mem->43.74 (MB)
adding     cur_mem->45.92 (MB)
adding     cur_mem->48.02 (MB)
adding     cur_mem->50.24 (MB)
adding     cur_mem->52.38 (MB)
adding     cur_mem->54.61 (MB)
adding     cur_mem->56.72 (MB)
store_clos cur_mem->35.73 (MB)

**Comment by FrancescAlted** [comment] 2016-05-05 11:34
Strange, it seems that `openFile` and such are definitively deprecated in forthcoming PyTables 3.3 (I am running the development branch).  Anyway, I can reproduce a similar behaviour in my box (Ubuntu 16.04), with the exception that I don't see the drop in memory consumption at the end.

Using compression (zlib, 1):

```
0
start      cur_mem->37.27 (MB)
adding     cur_mem->41.25 (MB)
adding     cur_mem->51.57 (MB)
adding     cur_mem->53.74 (MB)
adding     cur_mem->55.90 (MB)
adding     cur_mem->58.06 (MB)
adding     cur_mem->60.22 (MB)
adding     cur_mem->62.12 (MB)
adding     cur_mem->64.28 (MB)
adding     cur_mem->66.44 (MB)
adding     cur_mem->68.60 (MB)
store_clos cur_mem->68.26 (MB)
```

Without compression (filters=None):

```
0
start      cur_mem->37.52 (MB)
adding     cur_mem->41.16 (MB)
adding     cur_mem->51.22 (MB)
adding     cur_mem->53.38 (MB)
adding     cur_mem->55.55 (MB)
adding     cur_mem->57.71 (MB)
adding     cur_mem->59.60 (MB)
adding     cur_mem->61.76 (MB)
adding     cur_mem->63.93 (MB)
adding     cur_mem->66.09 (MB)
adding     cur_mem->68.25 (MB)
store_clos cur_mem->67.92 (MB)
```

so the behaviour is very close.  Now, in order to discard a leak somewhere in the compression pipeline, I raised n to 10000 and repeated the process:

With compression (blosc 1, for speed):

```
0
start      cur_mem->37.27 (MB)
adding     cur_mem->61.02 (MB)
adding     cur_mem->64.26 (MB)
adding     cur_mem->67.35 (MB)
adding     cur_mem->70.47 (MB)
adding     cur_mem->73.53 (MB)
adding     cur_mem->76.58 (MB)
adding     cur_mem->78.95 (MB)
adding     cur_mem->81.22 (MB)
adding     cur_mem->83.36 (MB)
adding     cur_mem->85.28 (MB)
store_clos cur_mem->79.63 (MB)
```

Without compression (filters=None):

```
0
start      cur_mem->37.15 (MB)
adding     cur_mem->60.67 (MB)
adding     cur_mem->63.91 (MB)
adding     cur_mem->66.99 (MB)
adding     cur_mem->70.05 (MB)
adding     cur_mem->73.19 (MB)
adding     cur_mem->76.25 (MB)
adding     cur_mem->78.97 (MB)
adding     cur_mem->80.93 (MB)
adding     cur_mem->82.91 (MB)
adding     cur_mem->84.85 (MB)
store_clos cur_mem->64.99 (MB)
```

So, memory usage is very close in one case and in the other, except for the case that for compression around ~80 MB are still allocated vs ~65 MB.  My guess is that the steady memory increment is mainly due to Python (and maybe HDF5) not getting rid of deallocated data structures (see https://github.com/FrancescAlted/DataContainersTutorials, specially chapter 1 and 2 for similar experiences).

Regarding the 15 MB of difference in the big case, my guess is that HDF5 is caching some internal buffers that are needed when using compression.  All in all, I don't see something specially scary in this, so I am going to close this.  Feel free to re-open if you find more compelling proofs of a leak though.

**Closed by FrancescAlted** 2016-05-05 11:34 UTC
