### ISSUE TITLE
unittest failure

### ISSUE THREAD

**Issue by MSardelich** [PyTables/PyTables#417] opened 2015-01-20 02:09 UTC
While **running unit tests Python VM crashes** (at test04d_delete method), as can be see below (``-v`` output):
```
 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Running BasicWriteTestCase.test04c_delete...
Nrows in /table0 : 10
Last selected value ==> 9
Total selected records in table ==> 10

ok
test04d_delete (__main__.BasicWriteTestCase)
Checking whether removing rows several times at once is working. ... Running BasicWriteTestCase.test04d_delete
-----------------------------------------

 -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Running BasicWriteTestCase.test04d_delete...
Nrows in /table0 : 95
Last selected value ==> 14
Total selected records in table ==> 15
```
Below the ``tables.print_version()``:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:  3.1.1
HDF5 version:      1.8.14
NumPy version:     1.9.1
Numexpr version:   2.4 (not using Intel's VML/MKL)
Zlib version:      1.2.3 (in Python interpreter)
LZO version:       2.06 (Aug 12 2011)
BZIP2 version:     1.0.6 (6-Sept-2010)
Blosc version:     1.4.0 (2014-07-04)
Blosc compressors: ['blosclz', 'lz4', 'lz4hc', 'snappy', 'zlib']
Cython version:    0.21.1
Python version:    2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)]
Platform:          Windows-7-6.1.7601-SP1
Byte-ordering:     little
Detected cores:    8
Default encoding:  ascii
Default locale:    (en_GB, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by FrancescAlted** [comment] 2015-04-18 12:53
I am unable to reproduce this:

```
$ PYTHONPATH=. python tables/tests/test_tables.py -v BasicWriteTestCase.test04d_delete 
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.0-rc1
HDF5 version:        1.8.12
NumPy version:       1.9.2
Numexpr version:     2.4.1 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.06 (Aug 12 2011)
Blosc version:       1.5.4 (2015-04-14)
Blosc compressors:   blosclz (1.0.3), lz4 (1.6.0), lz4hc (1.6.0), snappy (1.1.1), zlib (1.2.8)
Cython version:      0.22
Python version:      2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1]
Platform:            Linux-3.16.0-34-generic-x86_64-with-Ubuntu-14.10-utopic
Byte-ordering:       little
Detected cores:      4
Default encoding:    ascii
Default FS encoding: UTF-8
Default locale:      (ca_ES, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
test04d_delete (__main__.BasicWriteTestCase)
Checking whether removing rows several times at once is working. ... ok

----------------------------------------------------------------------
Ran 1 test in 0.044s

OK
```

Closing.  Please feel free to re-open this if you continue experiencing the problem.

**Closed by FrancescAlted** 2015-04-18 12:53 UTC
