### ISSUE TITLE
test failure output

### ISSUE THREAD

**Issue by mtwi** [PyTables/PyTables#269] opened 2013-07-31 20:57 UTC
tables-3.0.0
hdf5-1.8.11

   $ python setup.py build_ext --inplace

3. To run the test suite, set the PYTHONPATH environment variable to
   include the ``.`` directory, enter the Python interpreter and issue
   the commands::

    >>> import tables
    >>> tables.test()

   If there is some test that does not pass, please send the
   complete output for tests back to us.

--------- TEST FAILURE OUTPUT BELOW ----------

======================================================================
FAIL: test_enable_messages (tables.tests.test_basics.HDF5ErrorHandling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables/tests/common.py", line 154, in newmethod
    return oldmethod(self, *args, **kwargs)
  File "tables/tests/test_basics.py", line 2539, in test_enable_messages
    self.assertTrue("HDF5-DIAG" in stderr.decode('ascii'))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 5425 tests in 322.346s

**Comment by FrancescAlted** [comment] 2015-04-27 10:39
Too old, and I cannot reproduce it.  Closing.

**Closed by FrancescAlted** 2015-04-27 10:39 UTC
