### ISSUE TITLE
`45938 illegal hardware instruction` under Rosetta (new issue in 3.9.2)

### ISSUE THREAD

**Issue by peircej** [PyTables/PyTables#1186] opened 2024-07-30 08:42 UTC
For M1/M2 users of our application we push an Intel Python due to a couple of dependencies that don't have arm wheels (including tables, although it looks like that might change 🤞 )

So we're using tables under Rosetta

Unfortunately, in 3.9.2, that has stopped working and results in 
```
~ arch
i386
~ python
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
[1]    45938 illegal hardware instruction  python
```
We can't even do `try...except ImportError` because it's such a violent crash

I wonder if the recent changes to allow compatibility with Arm have accidentally broken Rosetta

**Comment by avalentino** [comment] 2024-07-30 09:28
Hi @peircej, thanks for reporting.
Sorry but I'm not sure to understand well the context.
What I can say for sure is that the current version of PyTables (v3.9.2) is not really new, it is being around since nov 2023.
The wheel for osx (intel), that I assume you are using, includes e.g. libblosc2 which is quite optimized and probably uses some intel specific SIMD instruction set which could be hard to manage by Rosetta.
I'm not sure, just trying to figure out what could be the problem.

From a practical point of view I do not have a mac so I cannot reproduce the issue.
Not sure how could I help in this specific case.

FYI conda-forge provides a PyTables v3.9.2 built for osx-arm.
Could be an option for you to switch to conda?

**Comment by peircej** [comment] 2024-07-30 09:36
Thanks for quick reply. Yes, I'm using the standard macos x86 wheels. There's another dependency of ours that fails to compile under arm so far, so we do need Rosetta.

I'll pin to 3.9.1 for now (which does import happily under Rosetta). 

At some point, I'll try and switch out the libblosc2 and if that doesn't work I'll try and find time to sit and compile/recompile the tables itself using bisect and try to work out exactly which commit between 3.9.1 and 3.9.2 broke things

**Comment by FrancescAlted** [comment] 2024-07-31 08:35
Yes, Rosetta emulation does not provide support for AVX2 instructions, and it is known that recent versions of Python-Blosc2 had issues with CPU lacking AVX2.  Fortunately this should have been fixed in latest Python-Blosc2 2.7.1.  Try it out and tell us if that works for you.

**Comment by larsoner** [comment] 2024-07-31 17:47
... looks like 2.7.1 was released yesterday, so in theory you can download the wheel from https://github.com/PyTables/PyTables/pull/1188 that is building right now and give it a shot @peircej

**Comment by larsoner** [comment] 2024-07-31 19:19
... for example you could try this artifact

https://github.com/PyTables/PyTables/actions/runs/10185263566/artifacts/1761502785

**Comment by peircej** [comment] 2024-08-01 08:50
Yes! Using the tables 3.9.3dev0 from that build artefact imports tables successfully under Rosetta:

with release 3.9.2 we have
```
(py310_x86) $ python                      
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
[1]    79397 illegal hardware instruction  python
```
now we have
```
(py310_x86) $ pip install /Users/lpzjwp/Downloads/cibw-wheels-macos-13-x86_64-1/tables-3.9.3.dev0-cp310-cp310-macosx_10_9_x86_64.whl 
...
Installing collected packages: tables
  Attempting uninstall: tables
    Found existing installation: tables 3.9.2
    Uninstalling tables-3.9.2:
      Successfully uninstalled tables-3.9.2
Successfully installed tables-3.9.3.dev0
(py310_x86) $ python
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tables
>>> tables.__version__
'3.9.3.dev0'
```

So it looks like this will be sorted in the next release, incorporating blosc2 2.7.1 
🥳

**Closed** 2024-08-08 10:13 UTC
Labels: help wanted, osx-arm64
