### ISSUE TITLE
open_file() does not support non-ascii pathnames

### ISSUE THREAD

**Issue by GHaccount123** [PyTables/PyTables#757] opened 2019-08-16 12:21 UTC
I cannot open a file with (I assume) non-ascii characters in the path name.

```
os.mkdir('ü')
h5file = tables.open_file('ü/b.h5', mode="w", title="pytable1")
```
gives the error
```
Unable to open/create file 'ü/b.h5'
```

The built-in open()-function and h5py.File() support them so this can be confusing, if no support of this is foreseen then perhaps add a more meaningful error message?

**Comment by avalentino** [comment] 2019-08-16 16:50
Dear @GHaccount123,
unfortunately I'm not able to reproduce your error.
Can you please post the complete error message (including the traceback)?
Also, can you please provide more information about your environment (OS, python version, pytables version)?
The output of the following command should be a good start:
```
python3 -c "import tables as tb; tb.print_versions()"
```

**Comment by GHaccount123** [comment] 2019-08-19 16:21
Hello,

the output is
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.5.2
HDF5 version:        1.10.4
NumPy version:       1.16.4
Numexpr version:     2.6.9 (using VML/MKL 2019.0.4)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.10 (Mar 01 2017)
BZIP2 version:       1.0.8 (13-Jul-2019)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.3), lz4hc (1.8.3), snappy (unknown), zlib (1.2.11), zstd (1.3.7)
Blosc filters:       shuffle, bitshuffle
Python version:      3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Platform:            Windows-10-10.0.16299-SP0
Byte-ordering:       little
Detected cores:      8
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (de_DE, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```
Moreover, according to the error back trace the error is thrown in H5FDsec2.c with the error message
```
unable to open file: name = 'ü/b.h5'
```

**Comment by avalentino** [comment] 2019-08-19 21:56
OK there seems to be nothing strange in your setup.
Unfortunately I do not have access to a windows machine so it is hard for me to track down the issue.
Can you please post the full traceback?
You should have a long traceback with a python specific part and a section regarding the C level HDF5 error stack.

**Comment by tomkooij** [comment] 2019-08-20 06:51
I can reproduce this. As stated by the TS, pytables cannot open a file with unicode in the path. Unicode in the filename is not an issue.

Full backtrace:

```python
In [3]: f = tables.open_file('füfoobar/b.h5', 'r')
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-3-79d58b21dc1e> in <module>
----> 1 f = tables.open_file('füfoobar/b.h5', 'r')

d:\Miniconda3\envs\py37\lib\site-packages\tables\file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    318
    319     # Finally, create the File instance, and return it
--> 320     return File(filename, mode, title, root_uep, filters, **kwargs)
    321
    322

d:\Miniconda3\envs\py37\lib\site-packages\tables\file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    782
    783         # Now, it is time to initialize the File extension
--> 784         self._g_new(filename, mode, **params)
    785
    786         # Check filters and set PyTables format version for new files.

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "..\src\H5F.c", line 509, in H5Fopen
    unable to open file
  File "..\src\H5Fint.c", line 1498, in H5F_open
    unable to open file: time = Tue Aug 20 08:47:13 2019
, name = 'füfoobar/b.h5', tent_flags = 0
  File "..\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "..\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'füfoobar/b.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0

End of HDF5 error back trace

Unable to open/create file 'füfoobar/b.h5'
```

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.5.2
HDF5 version:        1.10.5
NumPy version:       1.16.4
Numexpr version:     2.6.9 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.3), lz4hc (1.8.3), snappy (1.1.1), zlib (1.2.8), zstd (1.3.8)
Blosc filters:       shuffle, bitshuffle
Python version:      3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
Platform:            Windows-10-10.0.17134-SP0
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (nl_NL, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by tomkooij** [comment] 2019-08-20 07:09
Looks like an libhdf5 issue.

It seems `tables.utilsextension.encode_filename` work fine, but we maybe running into [this](https://forum.hdfgroup.org/t/non-english-characters-in-hdf5-file-name/4627/8) (or similar) libhdf5 issue.

**Comment by avalentino** [comment] 2019-08-20 17:36
@tomkooij thanks for investigating.
It seems that h5py implemented a workaround by means of  `filename_encode`/`filename_decode` functions (see h5py/h5py#841).

**Comment by tomkooij** [comment] 2019-08-20 18:34
@avalentino 
the h5py `filename_enode` is indeed different from pytables `encode_filename`:

```
In [28]: tables.utilsextension.encode_filename('füfoobar\\b.h5')
Out[28]: b'f\xc3\xbcfoobar\\b.h5'

In [29]: from os import fspath

In [30]: fspath('füfoobar\\b.h5').encode('mbcs', 'strict')
Out[30]: b'f\xfcfoobar\\b.h5'
```

I'll add this to the 3.6 milestone. I'll try and include a fix, but not really high-priority  (But perhaps @GHaccount123 can submit a PR?)

**Comment by avalentino** [comment] 2021-12-27 21:13
@GHaccount123, @tomkooij the `UnicodeFilename` test seems to pass in CI for fb13f07889e720.
Closing.
Please feel free to re-open if you still have problems with unicode pathnamess.

**Closed by avalentino** 2021-12-27 21:13 UTC
Labels: defect, windows, good first issues, help wanted
