### ISSUE TITLE
tables.tests.test_basics.UnicodeFilename failures on Windows.

### ISSUE THREAD

**Issue by mdickinson** [PyTables/PyTables#389] opened 2014-09-25 07:42 UTC
On the current 'develop' branch (commit bae4975a725fcb17dc7b6ced633962bbf48fd7da), we're seeing the test failures below on Windows 7 (64-bit), Python 2.7.3, HDF5 1.8.11.

Additional notes from a colleague here (@itziakos):

> update: the error takes place in the setUp method and the Error message is 
> (u"Unable to open/create file 'c:\users\itziakos\appdata\local\temp\para\u0140lelvbkwg0.h5'",)
> 
> more investigation shows that the original filename is correct but gets mangled as soon as it passes through https://github.com/PyTables/PyTables/blob/develop/tables/utilsextension.pyx#L599
> 
> Please note that on my machine the file system encoding arrives as the default for windows mbcs.

Failures and full version information below:

```
======================================================================
ERROR: test01 (tables.tests.test_basics.UnicodeFilename)
Checking creating a filename with Unicode chars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables\tests\test_basics.py", line 2341, in setUp
    self.h5file = tables.open_file(self.h5fname, "w")
  File "tables\file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 488, in tables.hdf5extension.File._g_new (tables\hdf5extension.c:4926)
HDF5ExtError: <unprintable HDF5ExtError object>

======================================================================
ERROR: test02 (tables.tests.test_basics.UnicodeFilename)
Checking  tables.is_hdf5_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables\tests\test_basics.py", line 2341, in setUp
    self.h5file = tables.open_file(self.h5fname, "w")
  File "tables\file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 488, in tables.hdf5extension.File._g_new (tables\hdf5extension.c:4926)
HDF5ExtError: <unprintable HDF5ExtError object>

======================================================================
ERROR: test03 (tables.tests.test_basics.UnicodeFilename)
Checking is_pytables_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables\tests\test_basics.py", line 2341, in setUp
    self.h5file = tables.open_file(self.h5fname, "w")
  File "tables\file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 488, in tables.hdf5extension.File._g_new (tables\hdf5extension.c:4926)
HDF5ExtError: <unprintable HDF5ExtError object>

======================================================================
ERROR: test_store_and_load_with_non_ascii_attributes (tables.tests.test_basics.UnicodeFilename)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tables\tests\test_basics.py", line 2341, in setUp
    self.h5file = tables.open_file(self.h5fname, "w")
  File "tables\file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "tables\file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "hdf5extension.pyx", line 488, in tables.hdf5extension.File._g_new (tables\hdf5extension.c:4926)
HDF5ExtError: <unprintable HDF5ExtError object>

----------------------------------------------------------------------
Ran 5724 tests in 370.993s
```

Version information:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:  3.1.2dev
HDF5 version:      1.8.11
NumPy version:     1.8.1
Numexpr version:   2.4 (using VML/MKL 10.3.1)
Zlib version:      1.2.3 (in Python interpreter)
Blosc version:     1.4.0 (2014-07-04)
Blosc compressors: blosclz (1.0.2), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Cython version:    0.20.2
Python version:    2.7.3 |EPD 7.3-1 (64-bit)| (default, Apr 12 2012, 15:20:16) [MSC v.1500 64 bit (AMD64)]
Platform:          Windows-7-6.1.7601-SP1
Byte-ordering:     little
Detected cores:    8
Default encoding:  ascii
Default locale:    (el_GR, cp1253)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by keszybz** [comment] 2015-01-08 18:57
It also fails on Linux with LANG=C (noticed while building Fedora package in mock environment):

```
$ LANG=C python bench/check_all.py
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:  3.1.2dev
HDF5 version:      1.8.13
NumPy version:     1.9.1
Numexpr version:   2.3 (not using Intel's VML/MKL)
Zlib version:      1.2.8 (in Python interpreter)
LZO version:       2.08 (Jun 29 2014)
BZIP2 version:     1.0.6 (6-Sept-2010)
Blosc version:     1.5.2 (2014-12-30)
Blosc compressors: blosclz (1.0.3), lz4 (1.4.0), lz4hc (1.4.0), snappy (unknown), zlib (1.2.8)
Cython version:    0.21.1
Python version:    2.7.9 (default, Dec 11 2014, 12:33:01) 
[GCC 4.9.2 20141101 (Red Hat 4.9.2-1)]
Platform:          Linux-3.18.0-0.rc7.git2.2.fc22.x86_64-i686-with-fedora-22-Rawhide
Byte-ordering:     little
Detected cores:    12
Default encoding:  ascii
Default locale:    (None, None)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
======================================================================
ERROR: test01 (tables.tests.test_basics.UnicodeFilename)
Checking creating a filename with Unicode chars.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1929, in setUp
    super(UnicodeFilename, self).setUp()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/common.py", line 421, in setUp
    self.h5fname = self._getTempFileName()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1926, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test02 (tables.tests.test_basics.UnicodeFilename)
Checking  tables.is_hdf5_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1929, in setUp
    super(UnicodeFilename, self).setUp()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/common.py", line 421, in setUp
    self.h5fname = self._getTempFileName()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1926, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test03 (tables.tests.test_basics.UnicodeFilename)
Checking is_pytables_file with a Unicode filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1929, in setUp
    super(UnicodeFilename, self).setUp()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/common.py", line 421, in setUp
    self.h5fname = self._getTempFileName()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1926, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

======================================================================
ERROR: test_store_and_load_with_non_ascii_attributes (tables.tests.test_basics.UnicodeFilename)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1929, in setUp
    super(UnicodeFilename, self).setUp()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/common.py", line 421, in setUp
    self.h5fname = self._getTempFileName()
  File "/builddir/build/BUILD/PyTables-16191801a53eddae8ca9380a28988c3b5b263c5e/build/lib.linux-i686-2.7/tables/tests/test_basics.py", line 1926, in _getTempFileName
    return tempfile.mktemp(prefix=self.unicode_prefix, suffix='.h5')
  File "/usr/lib/python2.7/tempfile.py", line 366, in mktemp
    if not _exists(file):
  File "/usr/lib/python2.7/tempfile.py", line 102, in _exists
    _stat(fn)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0140' in position 9: ordinal not in range(128)

----------------------------------------------------------------------
Ran 5730 tests in 276.098s

FAILED (errors=4, skipped=13)
```
It's probably the same issue. I don't think fixing it is that important, since if one is running in C locale, then it's their choice and not having Unicode filenames should be acceptable.

**Comment by avalentino** [comment] 2015-01-10 19:49
Hi @keszybz, thanks for contribute

> It's probably the same issue. I don't think fixing it is that important, since if one is running in C locale, then it's their choice and not having Unicode filenames should be acceptable.

I agree that do not makes sense to worry about failures of the UnicodeFilename test case in case of C locale.
Not sure anyway that the issue is the same of the windows case.

**Comment by avalentino** [comment] 2021-12-27 16:21
See also #757.

**Comment by avalentino** [comment] 2021-12-27 17:27
All tests seem to pass in CI, closing.

**Closed by avalentino** 2021-12-27 17:27 UTC
Labels: defect, windows, help wanted
