### ISSUE TITLE
Error updating Table 

### ISSUE THREAD

**Issue by duytrung** [PyTables/PyTables#450] opened 2015-05-07 10:51 UTC
Please provide compiled binary for manual installation of the package. Thank you very much!

Bug log:
```

C:\Python3\Scripts>pip install -U tables
Collecting tables
  Using cached tables-3.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Python3\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "C:\Python3\lib\distutils\msvc9compiler.py", line 259, in query_vcvarsall
        raise DistutilsPlatformError("Unable to find vcvarsall.bat")
    distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\eep1\AppData\Local\Temp\pip-build-1fov3on3\tables\setup.py", line 553, in <module>
        libraries=(package.library_name,))
      File "C:\Python3\lib\distutils\ccompiler.py", line 791, in has_function
        objects = self.compile([fname], include_dirs=include_dirs)
      File "C:\Python3\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Python3\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python3\lib\site-packages\setuptools\msvc9_support.py", line 62, in query_vcvarsall
        raise distutils.errors.DistutilsPlatformError(message)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).
    * Using Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
    * USE_PKGCONFIG: False

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in C:\Users\eep1\AppData\Local\Temp\pip-build-1fov3on3\tables
```

Kind regards

**Comment by andreabedini** [comment] 2015-05-08 01:07
PyTables contains compiled cython extensions and your system seems to be lacking the c compiler, I am no expert on Windows system but I found some instructions [here](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows) on how to compile cython extensions.

We don't have the infrastructure to provide binary packages yet, we could do it with appveyor, we are still working to set it up, see #426.

Closing as it's not a bug.

**Closed by andreabedini** 2015-05-08 01:07 UTC
