### ISSUE TITLE
BUG: setting a numpy array writeable not supported in numpy>=1.16

### ISSUE THREAD

**Issue by mattip** [PyTables/PyTables#719] opened 2019-01-18 10:15 UTC
In reading hdf5 data, [this line](https://github.com/PyTables/PyTables/blob/v3.4.4/tables/hdf5extension.pyx#L2155) is setting the `writable` flag of an ndarray to `True` which is dangerous and no longer allowed as of `numpy 1.16`. Is the line needed? The `buf` is a new copy, so it should be readwrite.

xref numpy/numpy#12791

**Comment by FrancescAlted** [comment] 2019-01-18 10:44
Yeah, it was probably me who did that many years ago.  I don't remember why I did that, but probably this is not longer needed with modern numpys.  Just out of curiosity, which is the reason why setting this flag on a read/write array is considered harmful?

**Comment by mattip** [comment] 2019-01-18 11:10
You may be allowing writing to readonly memory. The memory could be shared with another thread/process, it could be some random system memory so you can crash the process, it could be shared with some other python object. If python marked it readonly, it must have reasons. 

if needed you can do `bytearray[bytes]` to get a safe readwrite copy of `bytes`

**Comment by FrancescAlted** [comment] 2019-01-18 11:36
Ok, so IIUC the buffer that we are talking about is probably read-only, otherwise numpy should allowed us do the setting of the flag, right?  In that case, we can make use of the `bytearray[bytes]` trick.

**Comment by mattip** [comment] 2019-01-18 12:08
It would be better to use [np.array_frombuffer(buf, count, dtype='uint8').reshape(shape)](https://docs.scipy.org/doc/numpy/reference/generated/numpy.frombuffer.html) than np.array since that supports the buffer protocol, then you can use [PyMemoryView_FromMemory](https://docs.python.org/3/c-api/memoryview.html#c.PyMemoryView_FromMemory) to create the buffer.
Since you want a copy, you can do that after creating the ndarray:
```
np.array_frombuffer(buf, count, dtype='uint8').reshape(shape).copy()
```
There is also `PyMemoryView_FromBuffer` and [this page](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html) on cython and memoryviews

**Comment by avalentino** [comment] 2019-01-18 16:49
@FrancescAlted it seems to me that this issue is a duplicate of #718 and #717.
It has been already fixed in f6b64c9.

Probably the current fix can be improved but it already works AFAIK.

Probably we need to make a new delivery.

I'm closing. Please feel free to reopen if you think there is still some open point.

**Closed by avalentino** 2019-01-18 16:49 UTC
Labels: defect, duplicate

**Comment by FrancescAlted** [comment] 2019-01-18 16:52
Yeah, thanks for the reminder.  Yes, we need to do a release as soon as possible, but I am currently swamped.  Any volunteers?

**Comment by stevenwinfield** [comment] 2019-02-14 11:05
A new release would be really nice...

Thanks!

**Comment by pcko1** [comment] 2019-02-18 08:18
problem still persists, any fix?

**Comment by FrancescAlted** [comment] 2019-02-18 09:13
Yes, we know about the iusse, no need for more reminders, thanks :-)

BTW, if you really want to accelerate things in this front, please [consider making a donation]( 
https://numfocus.org/project/pytables).  Thanks!

**Comment by FrancescAlted** [comment] 2019-03-14 16:29
The new 3.5.1 release is out and this should be fixed.

**Comment by michaelaye** [comment] 2019-03-23 00:34
Interesting, it's not mentioned in the release notes for 3.5.1 that the fix is in? I think this is pretty much sufficiently important to be mentioned, considering how many people have HDF containers that became unreadable with the numpy 1.16 version because of this.

**Comment by avalentino** [comment] 2019-03-23 08:17
@michaelaye there is a small mention in the release notes for PyTables v3.5 (2119c44751d7632417b2c0dc69a20c683186529e). Maybe it is not visible enough actually.
Please feel free to suggest a better wording.

**Comment by michaelaye** [comment] 2019-03-24 01:05
That note is fine but I’m confused about its location, if this patch only went in at 3.5.1? That’s why I didn’t see it before.

**Comment by FrancescAlted** [comment] 2019-03-24 06:26
This patch actually went into 3.5.0.  Maybe the root of your confusion is that I screwed the wheels for 3.5.0 and had to release 3.5.1 just to fix the wheels. See https://github.com/PyTables/PyTables/issues/725.

**Comment by michaelaye** [comment] 2019-03-24 06:27
I see, thanks!
