### ISSUE TITLE
Request: Make Apple Silicon Wheels Available

### ISSUE THREAD

**Issue by padraic-padraic** [PyTables/PyTables#1165] opened 2024-05-14 09:28 UTC
Since #1050 was merged, the pipelines can now generate wheels for Apple Silicon. Would it be possible to (manually or othewise), add those to PyPI? Or would a new release need to be created, due to the fact that the wheels also include further changes from master?

**Comment by tamasgal** [comment] 2024-06-14 08:26
That would be great. There is no week without me having to explain users of my libraries which depend on PyTables how to fix the blosc2 problem (cf. https://github.com/PyTables/PyTables/issues/1134) by hand 🙈

**Comment by maxnoe** [comment] 2024-06-14 10:29
See 

- https://github.com/PyTables/PyTables/issues/1157
- https://github.com/PyTables/PyTables/issues/832
- https://github.com/PyTables/PyTables/pull/1050


The PR was merged April 18th. So we really "just" need a new release.

**Comment by maxnoe** [comment] 2024-06-14 10:30
In the mean time, arm64 builds are available via conda-forge: https://anaconda.org/conda-forge/pytables/files

**Comment by tamasgal** [comment] 2024-07-05 07:10
Any news on this?

**Comment by avalentino** [comment] 2024-07-05 07:18
Unfortunately the CI job producing the wheels is broken again (see https://github.com/PyTables/PyTables/actions).
Any help to fix it is more than welcome.

**Comment by maxnoe** [comment] 2024-07-05 11:07
It seems the issue is the target macos version of 10.9, it seems the libhdf5 is compiled with a newer target.

So I guess there are two solutions, making sure the libhdf5 is compiled with compatibility of 10.9 or raising the deployment target version.

Given that 10.x is EOL since a long time, probably raising the MACOS_DEPLOYMENT_TARGET is the easiest option.

**Comment by larsoner** [comment] 2024-07-05 15:33
I'll see if I can push some fixes in a new PR

**Comment by larsoner** [comment] 2024-07-05 16:14
One problem is going to be that `blosc` appears to only support 3.10+, see latest release

https://pypi.org/project/blosc2/2.7.0/#files

So it probably makes sense to also make PyTables depend on 3.10+

**Comment by maxnoe** [comment] 2024-07-05 19:20
That would be online with https://numpy.org/neps/nep-0029-deprecation_policy.html and also what I did here: #1160

**Comment by larsoner** [comment] 2024-07-05 19:27
:+1: makes sense @maxnoe , okay for me to start a new PR using what you have from #1160? In theory a squash+merge should preserve co-author history

**Comment by maxnoe** [comment] 2024-07-06 07:24
@larsoner please go ahead

**Closed** 2024-08-13 07:41 UTC
Labels: wheel, osx-arm64
