### ISSUE TITLE
"file is not writable" errors for files opened in read only mode

### ISSUE THREAD

**Issue by lrepiton** [PyTables/PyTables#914] opened 2021-12-01 16:33 UTC
When I close the PyTables file handle of a file in read only mode a flush function is called and I get an error  `tables.exceptions.FileModeError: the file is not writable`. PyTables should not try to write a file in read only mode.
This has already been discussed [here](https://github.com/PyTables/PyTables/issues/700#issuecomment-401029104) and I think this easy fix would be a good idea indeed. This problem seems to be the same as the one described in #910.

**Comment by avalentino** [comment] 2021-12-01 19:15
Hi @lrepiton, thanks for reporting.
A short code example reproducing the issue would help a lot.
If you could provide a patch it would help even mode :)

**Comment by lrepiton** [comment] 2021-12-06 14:41
Thanks @avalentino for your feedback. I have proposed a patch in pr #915 .

**Comment by avalentino** [comment] 2021-12-06 16:21
@lrepiton, just merged your patch
Thanks. lot

**Closed by avalentino** 2021-12-06 16:21 UTC

**Comment by jpjarnoux** [comment] 2022-06-01 09:31
Hi,
I got the same issue with the last release 3.7.0. I had a file only readable, and I opened it with the only read mode. Despite this I got an error because it's not writable. I assume that there is a miscalling in function. Below some more information.
```
"""
Traceback (most recent call last):
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/panorama/info/info.py", line 76, in run_info
    return mp_info(*args)
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/panorama/info/info.py", line 68, in mp_info
    pangenome.add_file(pan_file)
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/ppanggolin/pangenome.py", line 61, in add_file
    get_status(self, pangenome_file)
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/ppanggolin/formats/readBinaries.py", line 67, in get_status
    status_group._v_attrs.Partitioned = True
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/tables/attributeset.py", line 461, in __setattr__
    nodefile._check_writable()
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/tables/file.py", line 2112, in _check_writable
    raise FileModeError("the file is not writable")
tables.exceptions.FileModeError: the file is not writable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jarnoux/anaconda3/envs/dev/bin/panorama", line 8, in <module>
    sys.exit(main())
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/panorama/main.py", line 92, in main
    panorama.info.info.launch(args)
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/panorama/info/info.py", line 97, in launch
    for pangenome, modules_info in tqdm(p.imap_unordered(run_info, mp_args),
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
tables.exceptions.FileModeError: the file is not writable
```
It could be good to add a check if function is readable and call it if read only mode is used.
Thanks

**Comment by avalentino** [comment] 2022-06-01 09:45
Hi @jpjarnoux thanks for reporting.
In this case probably the multiprocessing environment could have a role.
I kindly ask toy to open a new issue and to report in more detail how to reproduce the issue.
A short and self contained example would be very appreciated.

**Comment by jpjarnoux** [comment] 2022-06-01 10:04
Hi,
Thanks, I will give more information in the new issue.

**Comment by jpjarnoux** [comment] 2022-06-01 11:27
@lrepiton I don't think so. I just tried on another folder and the same script working. I think that there is a problem with the file system. I'm going to search why because my files are with the same mode. Do you think that's possible, that's related to the h5 file ? When it was generated ? Because, I try to run script on old data.

**Comment by lrepiton** [comment] 2022-06-01 11:45
In your backtrace, don't you try to modify an attribute?
```
  File "/home/jarnoux/anaconda3/envs/dev/lib/python3.8/site-packages/ppanggolin/formats/readBinaries.py", line 67, in get_status
    status_group._v_attrs.Partitioned = True
```

**Comment by jpjarnoux** [comment] 2022-06-01 12:04
Ah yes ! That's the bug ! Thank you ! It's strange that it never happened before.
Thanks for your help and sorry for that !
