### ISSUE TITLE
Support for Apple's arm64 architecture (osx-arm64)

### ISSUE THREAD

**Issue by kartzke** [PyTables/PyTables#832] opened 2020-12-05 09:17 UTC
Hello, I get the following error when trying to install tables on a MacBook Pro with the M1 processor.  Part of the error shows PyTables supports ARM, but it failed to detect the CPU, so I'm guessing it's related to `osx-arm64`

`cpuinfo failed, assuming no CPU features: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.`

Here's the full error:

```
Collecting tables
  Using cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: /Users/ryan/miniforge3/envs/ft/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6g/73g1_dms191f5pj1mc5n8byh0000gn/T/pip-install-6weqp8s9/tables_6efa87f1030c473590e79b8388430fc1/setup.py'"'"'; __file__='"'"'/private/var/folders/6g/73g1_dms191f5pj1mc5n8byh0000gn/T/pip-install-6weqp8s9/tables_6efa87f1030c473590e79b8388430fc1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6g/73g1_dms191f5pj1mc5n8byh0000gn/T/pip-pip-egg-info-zbtiyiw2
         cwd: /private/var/folders/6g/73g1_dms191f5pj1mc5n8byh0000gn/T/pip-install-6weqp8s9/tables_6efa87f1030c473590e79b8388430fc1/
    Complete output (12 lines):
    /var/folders/6g/73g1_dms191f5pj1mc5n8byh0000gn/T/H5closeb4hby9yj.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        H5close();
        ^
    1 error generated.
    cpuinfo failed, assuming no CPU features: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
    * Using Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:57:00)
    * USE_PKGCONFIG: False
    * Found conda env: ``/Users/ryan/miniforge3/envs/ft``
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by avalentino** [comment] 2020-12-05 11:29
The problem seems to be that the setup script is unable to find the local installation of HDF5.
Hopefully something like the following should solve the issue:
```
$ conda indtall hdf5
```

**Comment by kartzke** [comment] 2020-12-05 13:13
Thanks for the quick reply, I'll give this a try when I'm back to my laptop next week and confirm

**Comment by kartzke** [comment] 2020-12-15 02:33
Looks like HDF5 doesn't support `osx-arm64` yet, I'll try to raise a ticket in that repo: 

https://anaconda.org/anaconda/hdf5

**Comment by avalentino** [comment] 2020-12-15 06:36
OK thanks @kartzke. I'm confident the it will be available soon. Please keep us informed.
I'm closing this issue because it seems there is nothing we can do until HDF5 is available.
Please feel free to reopen if you have other problems with the setup on osx-arm64

**Comment by yingzhu146** [comment] 2020-12-16 04:08
@avalentino I'm trying to build this from source running into some issues that are similar to #385 

pip and also cloning from source complain about missing header files:

```
1b330w0000gn/T/pip-pip-egg-info-0yh6c6uh
         cwd: /private/var/folders/rk/5hjbr45j7tv27cclp41b330w0000gn/T/pip-install-49ouaomn/tables_0a99f4ba274647b69b1440fee55aabea/
    Complete output (12 lines):
    /var/folders/rk/5hjbr45j7tv27cclp41b330w0000gn/T/H5closeiv750rzx.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        H5close();
        ^
```

I've tried `H5_DIR=/usr/local/ /Users/yingzhu/miniconda3/envs/python38/bin/python setup.py install`, `python setup.py install --hd5=/usr/local/`, and same via pip. I also tried just copying both dylibs and header files into the respective ./bin & ./include dirs of the miniconda env to no avail.

```
❯ grep -R H5close /usr/local/include
/usr/local/include/H5public.h:H5_DLL herr_t H5close(void);
```
So header files seem to be there, same with shared libs which I've successfully compiled from source for arm64

```
❯ file /usr/local/lib/libhdf5-shared.dylib
/usr/local/lib/libhdf5-shared.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

You've got some inspiration on what I might overlook here? 

Thanks a ton for all your work on this great OSS library, and your help here too

**Comment by avalentino** [comment] 2020-12-16 06:39
@yingzhu146 thanks for the additional info. I have re-opened the issue.

Please consider that I do not have access to an osx-arm64 machine myself so I can't reproduce the issue.
@FrancescAlted do you have a osx-arm64 laptop? 

It would help a lot if you could send the complete build log that you get when try to install pytables using ``setup.py`` directly.
The setup script is quite complex but prints some information that could be useful to understand what happens.
In particular I'm interested in the build and link commands.

I also need to know some system info e.g. the output of:
```
sys.platform()
platform.platform()
platform.python_version()
``` 
and also the compiler (clang ?) and its version.

Finally, which is the HDF5 version? I assume that it is installed in ``/usr/local`` but can you please if you are using a release or a debug build.

**Comment by yingzhu146** [comment] 2020-12-16 18:31
Thanks for checking this

```python
>>> platform.python_version()
'3.8.6'
>>> platform.platform()
'macOS-11.1-arm64-i386-64bit'
>>> sys.platform
'darwin'
```


```bash
❯ HDF5_DIR=/usr/local/ /Users/yingzhu/miniconda3/envs/python38/bin/python3.8
 setup.py &> log.out
❯ cat log.out
/var/folders/rk/5hjbr45j7tv27cclp41b330w0000gn/T/H5closedjyjg9fs.c:2:5: error
: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimp
licit-function-declaration]
    H5close();
    ^
1 error generated.
cpuinfo failed, assuming no CPU features: py-cpuinfo currently only works on
X86 and some PPC and ARM CPUs.
* Using Python 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:57
:00)
* USE_PKGCONFIG: True
* Found conda env: ``/Users/yingzhu/miniconda3``
.. ERROR:: Could not find a local HDF5 installation.
   You may need to explicitly state where your local HDF5 headers and
   library can be found by setting the ``HDF5_DIR`` environment
   variable or by using the ``--hdf5`` command-line option.

```

It's 10.12 - I built the release version with CMake - I've just realized that homebrew installed a x86 version at some point too - it might have gotten confused. investigating that now.

**Comment by avalentino** [comment] 2020-12-16 18:47
OK, thanks.
Please try 
```
export USE_PKGCONFIG=FALSE
```
or the equivalent command for you shell.

**Comment by yingzhu146** [comment] 2020-12-16 20:21
Thanks @avalentino! That didn't help but I fixed it like so:

1) remove my build - it seems there was some build error
2 ) use the prebuilt hdf5 arm package provided by macports (brew doesn't appear to have one)
3) install cblocs from conda forge with miniforge

Now it works.

Thanks for the help!

**Comment by avalentino** [comment] 2020-12-17 06:25
Thanks @yingzhu146

**Closed by avalentino** 2020-12-17 06:25 UTC
Labels: enhancement

**Comment by kartzke** [comment] 2021-03-01 13:40
@avalentino reopening this ticket.  Looks like HDF5 has a package built for apple silicon now:

HDF5 Github issue: https://github.com/HDFGroup/hdf5/issues/311
HDF5 forum link: https://forum.hdfgroup.org/t/apple-silicon-binaries-universal-binaries/7848/4

Does PyTables need H5PY?  If yes, then there's still a blocker, H5PY won't build from source on Apple Silicon yet due to dependency conflicts.  An example patch was proposed here, but it hasn't been discussed or merged yet : https://github.com/h5py/h5py/issues/1810

**Comment by avalentino** [comment] 2021-03-01 15:14
Hi @kartzke.
No PyTables do not needs h5py.
You need Mohave an HDF5 C library properly installed on your computer **and** need to tell to the setup.py script where it is (se also the [installation ](http://www.pytables.org/usersguide/installation.html) documentation)

**Comment by kartzke** [comment] 2021-03-02 15:49
Cool, I'll give it a go soon and report back, thanks!

**Comment by avalentino** [comment] 2021-03-02 16:47
> You need Mohave an HDF5 C ...

Sorry @kartzke the above is clearly a typo, it shone be "You need to have an HDF5 C ..."

**Comment by jonaswitt** [comment] 2021-08-06 07:00
I was stuck with a very similar problem using 

* an Apple Silicon Mac 
* Mac OS X 11.5.1
* Python 3.9.6
* pip 21.2.2
* A virtualenv environment
* `brew install hdf5 c-blosc lzo bzip2`

Running this command per the instructions ("by using the ``--hdf5`` command-line option"):

```
pip install --install-option='--hdf5=/opt/homebrew/opt/hdf5 --blosc=/opt/homebrew/opt/c-blosc --lzo=/opt/homebrew/opt/lzo --bzip2=/opt/homebrew/opt/bzip2' tables==3.6.1
```

would fail with the dreaded "Could not find a local HDF5 installation" error:

```
/Users/jonaswitt/Code/logutils/venv/lib/python3.9/site-packages/pip/_internal/commands/install.py:229: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting tables==3.6.1
  Using cached tables-3.6.1.tar.gz (4.6 MB)
    ERROR: Command errored out with exit status 1:
     command: python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/79/v840398d4dd2qsrks45m74g80000gn/T/pip-install-r4f461d1/tables_ba4095541ad1435aa2a97e17d5758b61/setup.py'"'"'; __file__='"'"'/private/var/folders/79/v840398d4dd2qsrks45m74g80000gn/T/pip-install-r4f461d1/tables_ba4095541ad1435aa2a97e17d5758b61/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/79/v840398d4dd2qsrks45m74g80000gn/T/pip-pip-egg-info-3fg516xb
         cwd: /private/var/folders/79/v840398d4dd2qsrks45m74g80000gn/T/pip-install-r4f461d1/tables_ba4095541ad1435aa2a97e17d5758b61/
    Complete output (11 lines):
    /var/folders/79/v840398d4dd2qsrks45m74g80000gn/T/H5closex_eawkny.c:2:5: error: implicit declaration of function 'H5close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        H5close();
        ^
    1 error generated.
    cpuinfo failed, assuming no CPU features: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
    * Using Python 3.9.6 (default, Jun 28 2021, 19:24:41)
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2b/32/847ee3f521aae6a0be380d923a736162d698586f444df1ac24b98c65025c/tables-3.6.1.tar.gz#sha256=49a972b8a7c27a8a173aeb05f67acb45fe608b64cd8e9fa667c0962a60b71b49 (from https://pypi.org/simple/tables/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tables==3.6.1 (from versions: 2.3, 2.3.1, 2.4.0, 3.0.0, 3.1.0, 3.1.1, 3.2.0rc1, 3.2.0rc2, 3.2.0, 3.2.1.1, 3.2.2, 3.2.3, 3.2.3.1, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.1, 3.5.2, 3.6.1)
ERROR: No matching distribution found for tables==3.6.1
```

Whereas using (identical) environment variables worked:

```
HDF5_DIR=/opt/homebrew/opt/hdf5 BLOSC_DIR=/opt/homebrew/opt/c-blosc LZO_DIR=/opt/homebrew/opt/lzo BZIP2_DIR=/opt/homebrew/opt/bzip2 pip install tables==3.6.1
```

This is probably _not_ a problem in tables, perhaps a problem in pip? 🤷‍♂️ But since the original poster seemed to use pip too, I thought it was worth mentioning for others with the same problem.

For what it's worth, I also checked out the tables-3.6.1 sources in the same environment and ran `python3 setup.py build --hdf5=/opt/homebrew/opt/hdf5 --blosc=/opt/homebrew/opt/c-blosc --lzo=/opt/homebrew/opt/lzo --bzip2=/opt/homebrew/opt/bzip2` which worked without any problems - but I normally prefer pip over the manual approach.

**Comment by avalentino** [comment] 2021-08-06 07:15
Hi @jonaswitt, thanks for reporting

**Comment by padraic-padraic** [comment] 2023-02-20 11:04
As a note, this is still an issue under Python 3.11. While simply exporting `HDF5_DIR=/opt/homebrew/opt/hdf5` is sufficient for me under python 3.10, I can't get compilation to work under 3.11.

Firstly, I again need to go back to specify the c-blosc, lzo and bzip-2 locations as mentioned above, However, even then, under Python 3.11 and Pip 23.0.1, I get the following error:
```
WARNING: Implying --no-binary=:all: due to the presence of --build-option / --global-option / --install-option. Consider using --config-settings for more flexibility.
DEPRECATION: --install-option is deprecated because it forces pip to use the 'setup.py install' command which is itself deprecated. pip 23.1 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11358
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting tables==3.8.0
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [244 lines of output]
      DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
      Collecting setuptools>=42.0
        Using cached setuptools-67.3.2.tar.gz (2.5 MB)
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting wheel
        Using cached wheel-0.38.4.tar.gz (67 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting oldest-supported-numpy
        Using cached oldest-supported-numpy-2022.11.19.tar.gz (4.9 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting packaging
        Using cached packaging-23.0.tar.gz (126 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting py-cpuinfo
        Using cached py-cpuinfo-9.0.0.tar.gz (104 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting Cython>=0.29.21
        Using cached Cython-0.29.33.tar.gz (2.1 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blosc2~=2.0.0
        Using cached blosc2-2.0.0.tar.gz (3.0 MB)
        Installing build dependencies: started
        Installing build dependencies: still running...
        Installing build dependencies: finished with status 'error'
        error: subprocess-exited-with-error

        × pip subprocess to install build dependencies did not run successfully.
        │ exit code: 1
        ╰─> [185 lines of output]
            DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
            Collecting setuptools
              Using cached setuptools-67.3.2.tar.gz (2.5 MB)
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting scikit-build
              Using cached scikit-build-0.16.7.tar.gz (274 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting cython
              Using cached Cython-0.29.33.tar.gz (2.1 MB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting cmake
              Using cached cmake-3.25.2.tar.gz (33 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting ninja
              Downloading ninja-1.11.1.tar.gz (27 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting oldest-supported-numpy
              Using cached oldest-supported-numpy-2022.11.19.tar.gz (4.9 kB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting distro
              Using cached distro-1.8.0.tar.gz (59 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Installing backend dependencies: started
              Installing backend dependencies: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting packaging
              Using cached packaging-23.0.tar.gz (126 kB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'done'
              Preparing metadata (pyproject.toml): started
              Preparing metadata (pyproject.toml): finished with status 'done'
            Collecting wheel>=0.32.0
              Using cached wheel-0.38.4.tar.gz (67 kB)
              Preparing metadata (setup.py): started
              Preparing metadata (setup.py): finished with status 'done'
            Collecting numpy==1.23.2
              Using cached numpy-1.23.2.tar.gz (10.7 MB)
              Installing build dependencies: started
              Installing build dependencies: finished with status 'done'
              Getting requirements to build wheel: started
              Getting requirements to build wheel: finished with status 'error'
              error: subprocess-exited-with-error

              × Getting requirements to build wheel did not run successfully.
              │ exit code: 1
              ╰─> [95 lines of output]
                  <string>:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
                  Running from numpy source directory.
                  <string>:86: DeprecationWarning:

                    `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
                    of the deprecation of `distutils` itself. It will be removed for
                    Python >= 3.12. For older Python versions it will remain present.
                    It is recommended to use `setuptools < 60.0` for those Python versions.
                    For more details, see:
                      https://numpy.org/devdocs/reference/distutils_status_migration.html


                  running egg_info
                  running build_src
                  INFO: build_src
                  creating numpy.egg-info
                  writing numpy.egg-info/PKG-INFO
                  writing dependency_links to numpy.egg-info/dependency_links.txt
                  writing entry points to numpy.egg-info/entry_points.txt
                  writing top-level names to numpy.egg-info/top_level.txt
                  writing manifest file 'numpy.egg-info/SOURCES.txt'
                  /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py:643: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
                  Please extend command classes from setuptools instead of distutils.
                    warnings.warn(
                  INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
                  Traceback (most recent call last):
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                      main()
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                      json_out['return_val'] = hook(**hook_input['kwargs'])
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                      return hook(config_settings)
                             ^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
                      return self._get_build_requires(config_settings, requirements=['wheel'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
                      self.run_setup()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 485, in run_setup
                      self).run_setup(setup_script=setup_script)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
                      exec(code, locals())
                    File "<string>", line 493, in <module>
                    File "<string>", line 485, in setup_package
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
                      return distutils.core.setup(**attrs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
                      return run_commands(dist)
                             ^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                      dist.run_commands()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                      self.run_command(cmd)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
                      super().run_command(command)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                      cmd_obj.run()
                    File "/private/var/folders/ps/dwlk96k15fl7_csnxt2q57dc0000gn/T/pip-install-se5mtmkp/numpy_e6c0a52c426d425ea06850a820c627f6/numpy/distutils/command/egg_info.py", line 25, in run
                      _egg_info.run(self)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 308, in run
                      self.find_sources()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
                      mm.run()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 560, in run
                      self.add_defaults()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
                      sdist.add_defaults(self)
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
                      self._add_defaults_build_sub_commands()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
                      self.filelist.extend(chain.from_iterable(files))
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 503, in extend
                      self.files.extend(filter(self._safe_path, paths))
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
                      files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
                      cmds = (self.get_finalized_command(c) for c in missing_cmds)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
                      cmd_obj.ensure_finalized()
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
                      self.finalize_options()
                    File "/private/var/folders/ps/dwlk96k15fl7_csnxt2q57dc0000gn/T/pip-install-se5mtmkp/numpy_e6c0a52c426d425ea06850a820c627f6/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
                      v = getattr(c, a)
                          ^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
                      return _build_ext.build_ext.__getattr__(self, name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
                      raise AttributeError(attr)
                  AttributeError: fcompiler. Did you mean: 'compiler'?
                  [end of output]

              note: This error originates from a subprocess, and is likely not a problem with pip.
            error: subprocess-exited-with-error

            × Getting requirements to build wheel did not run successfully.
            │ exit code: 1
            ╰─> See above for output.

            note: This error originates from a subprocess, and is likely not a problem with pip.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × pip subprocess to install build dependencies did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```

It's possible this is a setuptools issue, as this is the only other recent google hit for the error: https://github.com/pypa/setuptools/issues/3549

**Comment by cbrnr** [comment] 2023-09-05 11:58
May I ask if anything is still blocking the release of wheels for macOS ARM64? It would be so much more convenient if `pip install tables` just worked.

**Comment by avalentino** [comment] 2023-09-05 12:26
We will have a release relatively soon but please note that, at the moment, we do not have a way to build wheels to wheels for MacOS ARM in GHA, so you will still need to build pytables from sources on that platform.

**Comment by avalentino** [comment] 2023-09-05 12:38
@cbrnr thanks a lot for the link.
We indeed use cibuildwheel, but in the past we hade problems with building of wheels for OSX-arm so we gave up.
Maybe we could try again for this release.

By the way I personally have not the possibility to troubleshoot (and very limited time), so a PR to enable OSX-ARM wheels in GHA would be really appreciated.

**Comment by cbrnr** [comment] 2023-09-05 12:43
That's great if you already use it! Maybe just enabling it now will work (fingers crossed)? I can try and submit a PR, sure.

Just for context, I think macOS ARM64 builds are pretty important now, because Apple is not producing Intel-based machines anymore. So a wheel for that platform would be greatly appreciated by many people I think.

**Comment by avalentino** [comment] 2023-09-05 13:27
@cbrnr I agree, it would be a great addition for the next release!

**Comment by dkfellows** [comment] 2023-09-29 12:07
This appears to be related to:
* https://github.com/pypa/setuptools/issues/3549

**Comment by cbrnr** [comment] 2023-09-29 13:04
I don't think that's the issue. *All* packages seem to be built with the wrong architecture, the most recent discussion is in #1049.
