### ISSUE TITLE
HDF5 1.10 breaks pytables 3.2.2

### ISSUE THREAD

**Issue by dsteinberg** [PyTables/PyTables#545] opened 2016-05-03 03:18 UTC
On Arch Linux HDF5 was just upgraded to 1.10. This seems to break array creation. E.g.

```
>>> f2 = tables.open_file('test.hdf5', 'w')
>>> f2.create_array('/', 'test', obj=np.random.randn(100))
```

Gives the following error,

```
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-4-509467cf97dc> in <module>()
----> 1 f2.create_array('/', 'test', obj=np.random.randn(100))

/home/dsteinberg/.virtualenvs/uncover-ml/lib/python3.5/site-packages/tables/file.py in create_array(self, where, name, obj, title, byteorder, createparents, atom, shape)
   1150         parentnode = self._get_or_create_path(where, createparents)
   1151         return Array(parentnode, name,
-> 1152                      obj=obj, title=title, byteorder=byteorder)
   1153 
   1154     createArray = previous_api(create_array)

/home/dsteinberg/.virtualenvs/uncover-ml/lib/python3.5/site-packages/tables/array.py in __init__(self, parentnode, name, obj, title, byteorder, _log, _atom)
    185         # Ordinary arrays have no filters: leaf is created with default ones.
    186         super(Array, self).__init__(parentnode, name, new, Filters(),
--> 187                                     byteorder, _log)
    188 
    189     def _g_create(self):

/home/dsteinberg/.virtualenvs/uncover-ml/lib/python3.5/site-packages/tables/leaf.py in __init__(self, parentnode, name, new, filters, byteorder, _log)
    260         # is a lazy property that automatically handles their loading.
    261 
--> 262         super(Leaf, self).__init__(parentnode, name, _log)
    263 
    264     def __len__(self):

/home/dsteinberg/.virtualenvs/uncover-ml/lib/python3.5/site-packages/tables/node.py in __init__(self, parentnode, name, _log)
    265             #   Create or open the node and get its object ID.
    266             if new:
--> 267                 self._v_objectid = self._g_create()
    268             else:
    269                 self._v_objectid = self._g_open()

/home/dsteinberg/.virtualenvs/uncover-ml/lib/python3.5/site-packages/tables/array.py in _g_create(self)
    217             # on
    218             (self._v_objectid, self.shape, self.atom) = self._create_array(
--> 219                 nparr, self._v_new_title, self.atom)
    220         except:  # XXX
    221             # Problems creating the Array on disk. Close node and re-raise.

tables/hdf5extension.pyx in tables.hdf5extension.Array._create_array (tables/hdf5extension.c:14170)()

HDF5ExtError: Problems creating the Array.
```

Downgrading HDF5 from 1.10 -> 1.8 fixes the issue. Sorry if this is already known!

Thanks!

**Comment by FrancescAlted** [comment] 2016-05-03 08:30
Yep, I can reproduce the issue in my Ubuntu box, even when compiling HDF5 1.10.0 with `./configure --with-default-api-version=v18`.  That's bad, because that should have been enough for backward compatibility (see https://www.hdfgroup.org/HDF5/doc/ADGuide/Changes.html).  For the time being, it would be best to explicitly warn against HDF5 1.10 usage in PyTables.  Other thoughts?

**Comment by andreabedini** [comment] 2016-05-03 12:52
😞 the question is where to put the warning, is this issue visible enough or you're planning to make a quick release?

**Comment by FrancescAlted** [comment] 2016-05-03 13:22
Yeah, better than a warning it would be better if PyTables just refuse to compile/work if HDF5 1.10 is found.  Also, note that I tested with Ubuntu 16.04 which comes with gcc 5.3.1, which is new and would be nice if this can be tested in another box (with gcc < 5 for example).

Regarding the release, I am not specially pressed, but several fixes and improvements are already in the develop branch, so yeah, a release would be nice rather sooner than later.

**Comment by enckse** [comment] 2016-05-10 18:32
FYI - anyone using arch (as of today) who has all packages updated (e.g. pandas/pytables/hdf) is potentially going to hit this. Per this [issue](https://github.com/pydata/pandas/issues/13127)

**Comment by tastyminerals** [comment] 2016-05-10 18:45
I confirm, **manjaro** (arch spin off) is also affected.

**Comment by enckse** [comment] 2016-05-28 14:26
Able to workaround this by installing the hdf5_18 package in arch (and no longer having to ignore pytables/hdf5 updates), per comment [here](https://bugs.archlinux.org/task/49212?project=1&cat%5B0%5D=2&string=hdf5)

**Comment by chiraganand** [comment] 2016-06-08 07:18
I was also finally able to compile pytables on Arch. This is what I did:

1. Installed HDF5 1.8.17 into /usr/local, can't afford to remove 1.10 from /usr.
2. Patched setup.py following #406 because pip would not pay heed to `--hdf5` or any other environment variables and always link like `-L/usr -lhdf5`. I figured that it is a setup.py issue. After doing this I was able to compile and install.
3. python setup.py build && python setup.py install

Now it is getting stuck when I do tables.test(). Apparently it is trying to use `dict.iteritems()` which is not there in Python3?

```
>>> import tables
>>> tables.test()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.2.2
HDF5 version:        1.8.17
NumPy version:       1.11.0
Numexpr version:     2.6.0 (not using Intel's VML/MKL)
Zlib version:        1.2.8 (in Python interpreter)
LZO version:         2.09 (Feb 04 2015)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.4.4 (2015-05-05)
Blosc compressors:   blosclz (1.0.2.1), lz4 (1.2.0), lz4hc (1.2.0), snappy (1.1.1), zlib (1.2.8)
Python version:      3.5.1 (default, Mar  3 2016, 09:29:07)
[GCC 5.3.0]
Platform:            Linux-4.4.11-1-lts-x86_64-with-arch
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: ascii
Default locale:      (None, None)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Performing only a light (yet comprehensive) subset of the test suite.
If you want a more complete test, try passing the --heavy flag to this script
(or set the 'heavy' parameter in case you are using tables.test() call).
The whole suite will take more than 4 hours to complete on a relatively
modern CPU and around 512 MB of main memory.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".venv/lib/python3.5/site-packages/tables-3.2.2-py3.5-linux-x86_64.egg/tables/tests/test_all.py", line 102, in test
result = unittest.TextTestRunner(verbosity=1+int(verbose)).run(suite())
File ".venv/lib/python3.5/site-packages/tables-3.2.2-py3.5-linux-x86_64.egg/tables/tests/test_all.py", line 70, in suite
__import__(name)
File ".venv/lib/python3.5/site-packages/tables-3.2.2-py3.5-linux-x86_64.egg/tables/tests/test_enum.py", line 212, in <module>
class EnumTableTestCase(common.TempFileMixin, TestCase):
File ".venv/lib/python3.5/site-packages/tables-3.2.2-py3.5-linux-x86_64.egg/tables/tests/test_enum.py", line 215, in EnumTableTestCase
enum = tables.Enum({'red': 4, 'green': 2, 'blue': 1, 'black': 0})
File ".venv/lib/python3.5/site-packages/tables-3.2.2-py3.5-linux-x86_64.egg/tables/misc/enum.py", line 128, in __init__
for (name, value) in enum.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by avalentino** [comment] 2016-06-09 05:42
Please make sure to run the test when you are outside of the source tree:

```
$ python setup.py install
$ cd ..
$ python -c "import tables; tables.test()"
```

**Comment by chiraganand** [comment] 2016-06-09 07:51
Yes, I am outside of the source tree. I even tried it from $HOME.

**Comment by tomkooij** [comment] 2016-06-28 09:25
@chiragrand: Please note that on current `master` python 2 -> 3 conversion is done by `lib2to3`. The output is in `build/lib-XXX/` where XXX is the build-id-version-string. Your issue with `iteritems()` seems to indicate your are running the tests in the original (python2) source tree.

This is my workflow on python 3:
```
$ python setup.py develop --hdf5=/path/to/hdf5
$ cd build/lib.linux-x86_64-3.5
$ python tables/tests/test_all.py
```

**Comment by chiraganand** [comment] 2016-06-29 09:24
@tomkooij Yes, the error is now gone. I was able to run the tests from build/lib.linux-XXX directory.

**Comment by subito-git** [comment] 2016-09-07 11:49
anybody please help me to install hdf5-1.10.0  in my ubuntu 16.04

**Comment by andreabedini** [comment] 2016-09-08 00:58
@subito-git I suggest you to seek help from the HDFGroup (which develops and maintains HDF5). Either contact the helpdesk at help@hdfgroup.org or use the [user mailing list](https://www.hdfgroup.org/services/community_support.html).

**Comment by pini-gh** [comment] 2016-10-20 22:13
Hi,
Any plan to add support for support HDF5 1.10? I'd like upcoming Debian Stretch ships with this release, and pytables seems the last showstopper from the about 90 HDF5 reverse dependencies.

**Comment by molofishy** [comment] 2016-12-12 23:05
Just found this page. I'm also experiencing this issue as explained [here](http://stackoverflow.com/questions/41099426/saving-pandas-dataframe-as-hdf5?noredirect=1#comment69404644_41099426).

**Comment by avalentino** [comment] 2016-12-13 06:41
@molofishy this issue is fixed now in the development branch.
Do you still have problems with pandas if you use the development version of PyTables?

**Comment by molofishy** [comment] 2016-12-13 08:37
@avalentino I tried installing the development version of PyTables with `pip install git+https://github.com/PyTables/PyTables`. The below error results even though I have already installed hdf5-1.10.0 with `pkg install hdf5-1.10.0`

```
    /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    tables/utilsextension.c:277:10: fatal error: 'hdf5.h' file not found
    #include "hdf5.h"
             ^
    1 warning and 1 error generated.
    error: command 'cc' failed with exit status 1
```

**Comment by ohlookemus** [comment] 2017-02-28 18:21
@molofishy This worked for me.

pip install -e git+https://github.com/PyTables/PyTables@develop#egg=tables

**Closed** 2017-04-11 18:32 UTC
Labels: defect

**Comment by zxweed** [comment] 2017-06-25 13:42
try this command:
`pip install tables --install-option="--hdf5=/home/user/hdf5.1.10"`
