### ISSUE TITLE
strange `Segmentation fault` caused by pytables import order

### ISSUE THREAD

**Issue by braindevices** [PyTables/PyTables#662] opened 2018-01-03 10:59 UTC
importing pytables before matplotlib and numpy causes `Segmentation fault` or `libpng error: IDAT: bad parameters to zlib` when try to plot data. I create a [demo](https://github.com/braindevices/pytable_mpl_np_bugs) to show this strange bug.
I load the data frame from h5f file then try to use `quiver()` to plot it (but not limited to just quiver). The larger the data frame the easier the segmentation falut shows. If the data is small it just show  `libpng error: IDAT: bad parameters to zlib`.

```
python demo_pytb_mpl_importorder.py -h
usage: demo_pytb_mpl_importorder.py [-h] [-v] [--create_data]
                                    [--nt number_of_frame]
                                    [--nj number_of_rows]
                                    [--ni number_of_cols] [--demo_bug]
                                    [--demo_ok]

show strange bugs of pytables import order

optional arguments:
  -h, --help            show this help message and exit
  -v, --verbose         set verbosity level [default: None]
  --create_data         create test data in ./ [default: False]
  --demo_bug            demonstrate the bug [default: False]
  --demo_ok             demonstrate the normal case [default: False]

  --nt number_of_frame  create test data with nt frames >=2 [default: 2]
  --nj number_of_rows   create test data with nj rows >=2 [default: 3000]
  --ni number_of_cols   create test data with ni cols >=2 [default: 4000]
```
Here is the result:
 ```
python demo_pytb_mpl_importorder.py --create_data --nj 1500 --ni 2000
data
data shape = [2 1500 2000]

python demo_pytb_mpl_importorder.py --demo_bug
bug
pytable version:  3.4.2
import pytables before matplotlib and numpy causes `Segmentation fault` or `libpng error: IDAT: bad parameters to zlib`
numpy version:  1.13.3
mpl version:  2.1.1 plt with backend:  Qt5Agg
read file
(1500, 2000)
try to create fig
Segmentation fault
python demo_pytb_mpl_importorder.py --demo_ok
OK
import pytables after matplotlib or after numpy is OK: 
mpl version:  2.1.1 plt with backend:  Qt5Agg
pytable version:  3.4.2
read file
(1500, 2000)
try to create fig
figure creation is OK
figure creation is OK
Closing remaining open files:test_data.h5...done


```
if we use data size 300x400, it only shows the zlib error:
```
python demo_pytb_mpl_importorder.py --demo_bug
bug
pytable version:  3.4.2
import pytables before matplotlib cause Segmentation fault
numpy version:  1.13.3
mpl version:  2.1.1 plt with backend:  Qt5Agg
read file
(300, 400)
try to create fig
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
libpng error: IDAT: bad parameters to zlib
figure creation is OK
Closing remaining open files:test_data.h5...done
```

**Comment by avalentino** [comment] 2018-04-27 18:07
This seems to be a duplicate of #686 and #644

**Closed by avalentino** 2018-04-27 18:07 UTC
Labels: duplicate
