### ISSUE TITLE
odd string attribute behavior

### ISSUE THREAD

**Issue by kcw78** [PyTables/PyTables#831] opened 2020-11-27 17:28 UTC
I am working with an HDF5 file created by an upstream application (written by a commercial application in C++). It adds 7 attributes to a Group; 6 are "strings" and 1 is an integer array. I have discovered some odd behavior with the string attributes:
1) When I access with `Groupname._v_attrs[name]`, one is is returned as type `<class 'str'>` and the other 5 are returned as type `<class 'numpy.bytes_'>`. I also checked with h5py, I get type `<class 'str'>` for all 6 string attributes. I contacted the developer, and all strings are created with the same code.
2) There is a semi-related issue. The 5 `numpy.bytes_` attributes are retrieved in the **user** attribute set and the `<class 'str'>` attribute is retrieved in the **system** attribute set. Any connection to the first issue?

I also checked the group attributes with h5dump and ptdump. h5dump output shows no difference in attributes (only the STRSIZE of each attribute changes). ptdump output matches comments above (5 of 6 string attributes are :=b'string_chars', and the sixth is simply:= 'chars'; not b'chars'). 

Attached ZIP file is an example. Check attributes on Group: /NASTRAN.
[instest2019fp1.zip](https://github.com/PyTables/PyTables/files/5609033/instest2019fp1.zip)

For reference, here is the code snippet I am using to read the attributes.
```
import tables as tb
with tb.File('instest2019fp1.h5','r') as h5f:
    nast_grp=h5f.root.NASTRAN

    print ('\nAll Attributes')
    for name in nast_grp._v_attrs._f_list(attrset='all'):
        print (name,':',type(nast_grp._v_attrs[name]))
        print(f'{name}:{nast_grp._v_attrs[name]}' )
        
    print ('\nUser Attributes')
    for name in nast_grp._v_attrs._f_list(attrset='user'):
        print(f'{name}:{nast_grp._v_attrs[name]}' )
        
    print ('\nSystem Attributes')
    for name in nast_grp._v_attrs._f_list(attrset='sys'):
        print(f'{name}:{nast_grp._v_attrs[name]}' )
```

**Comment by avalentino** [comment] 2020-11-28 10:19
Hi @kcw78 thanks for reporting.
OK, I have checked the code and it seems that the current one is an intended behaviour.

https://github.com/PyTables/PyTables/blob/78a327dafa1086aedb88964510aa69cb68657f4b/tables/hdf5extension.pyx#L212

The general rule for attributes is that only the ones for which the character set has been explicitly set to ``H5T_CSET_UTF8`` are translated into Python strings. Other ones are treated as bytes for compatibility reasons (up to HDF5 v1.8 there was no way to specify the encoding of a string, so, in principle, people performed the encoding by itself).

PyTables system attributes are treated in a different way because they are supposed to be totally controlled by PyTables itself. The encoding of that attributes is known to PyTables so it is possible to decode them into Python strings safely.
PyTables system attributes are always Python strings

Looking at your dataset (the relevant part of the dump is below), all attributes have ``CSET H5T_CSET_ASCII`` so they are treated as bytes.
``VERSION`` is one of the PyTables system attributes (even if in your case I don't know if it is intended or if it is as name clash) , so it is converted into ``str``.

```
HDF5 "instest2019fp1.h5" {
GROUP "/NASTRAN" {
   ATTRIBUTE "ARCH" {
      DATATYPE  H5T_STRING {
         STRSIZE 8;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "win64i8"
      }
   }
   ATTRIBUTE "HOSTNAME" {
      DATATYPE  H5T_STRING {
         STRSIZE 9;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "L01065-2"
      }
   }
   ATTRIBUTE "IFPSTAR" {
      DATATYPE  H5T_STRING {
         STRSIZE 4;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "YES"
      }
   }
   ATTRIBUTE "INPUT" {
      DATATYPE  H5T_STRING {
         STRSIZE 12;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "instest.dat"
      }
   }
   ATTRIBUTE "SOL" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): 101
      }
   }
   ATTRIBUTE "TIME" {
      DATATYPE  H5T_STRING {
         STRSIZE 33;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "Tue Nov 24 09:21:15 2020 (UTC-6)"
      }
   }
   ATTRIBUTE "VERSION" {
      DATATYPE  H5T_STRING {
         STRSIZE 9;
         STRPAD H5T_STR_NULLTERM;
         CSET H5T_CSET_ASCII;
         CTYPE H5T_C_S1;
      }
      DATASPACE  SCALAR
      DATA {
      (0): "msc20191"
      }
   }
   [CUT]
}
}
```

If you are interested in having attributes treated as Python strings in PyTablles and you have not have other constraints you could specify the ``H5T_CSET_UTF8`` encoding when you write attributes at C++ level.

Closing the issue.
Please reopen if you thin there is something different that can be done in PyTables.

**Closed by avalentino** 2020-11-28 10:19 UTC

**Comment by kcw78** [comment] 2020-11-30 01:43
Hi Antonio,
Thanks for researching this and providing a very detailed explanation.
The use of a system reserved attribute (VERSION) was unintended, and the
associated behavior explains what I'm seeing.
And, it explains why I see different behavior with PyTables and h5py.
So, 2 mysteries solved at the same time. :-)

FYI, I am fine with the use of H5T_CSET_ASCII (vs H5T_CSET_UTF8 ), and
subsequent need of the user to handle encoding.. There are international
users of the commercial software, and many may NOT want UTF8 encoding.
Thanks!
Regards,
-Ken Walker
