### ISSUE TITLE
PyPI source (sdist) ships compiled libblosc2.so

### ISSUE THREAD

**Issue by bnavigator** [PyTables/PyTables#1001] opened 2023-02-25 01:05 UTC
The currently published source distribution on PyPI ships the compiled Unix library `tables-3.8.0/tables/libblosc2.so`.

**Comment by avalentino** [comment] 2023-02-25 07:23
Thanks for reporting.
I will try to address it ASAP.

**Comment by avalentino** [comment] 2023-02-26 07:59
The issue seems to be already fixed in the current master branch.

**Closed by avalentino** 2023-02-26 07:59 UTC
Labels: defect

**Comment by bnavigator** [comment] 2023-02-27 03:11
Are you sure? The current master branch CI still has the following output when creating the sdist:

```
  * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
 ```

So it seems to be intentional. It should not be. Sdists are for sources, not for platform dependent libraries.

**Comment by avalentino** [comment] 2023-02-27 07:04
I can confirm that, despite the message, no ".so" file is include din the source distribution now generated with `make dist`.
The "libblosc2.so" file is in the local source tree after the build but not included in the sdist.
