### ISSUE TITLE
pip install failed: no module named cpuinfo

### ISSUE THREAD

**Issue by Dapid** [PyTables/PyTables#562] opened 2016-07-05 07:20 UTC
I tried to update from 3.2.2 to 3.2.3, but I am getting the following error:

```
$ pip install -U tables
Collecting tables
  Using cached tables-3.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zkFlL8/tables/setup.py", line 34, in <module>
        import cpuinfo
    ImportError: No module named cpuinfo
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-zkFlL8/tables/
```

It happens with both Python 2.7.11 and 3.4.3 on Linux.

**Comment by tomkooij** [comment] 2016-07-05 07:31
Thanks for reporting! I will investigate.

**Comment by tomkooij** [comment] 2016-07-05 07:39
@Dapid Could you try 'pip install py-cpuinfo' and check if 'pip install -U tables' works after that?

It seems we need to add `py-cpuinfo` to `requirements.txt`

`py-cpyinfo' is included in the base 'conda' installation of python 2.7 and 3.4 so I'm not getting the error.

Please let me know if this works for you.

**Comment by andreabedini** [comment] 2016-07-05 07:49
@tomkooij @FrancescAlted suggested that `cpuinfo.py` (that is included with PyTables) is not included in the `MANIFEST.in` file and therefore not included in the source tarball. You can check yourself doing `tar tzf tables-3.2.3.tar.gz | grep cpuinfo`. Yay for a quick 3.2.4! :)

**Comment by Dapid** [comment] 2016-07-05 08:17
@tomkooij  it fails in a different place.

```
  Failed building wheel for tables
Command "/home/david/.local/virtualenv/py27/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-weKxCL/tables/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FrTOeV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/david/.local/virtualenv/py27/include/site/python2.7/tables" failed with error code 1 in /tmp/pip-build-weKxCL/tables/
```

Here is the full log:
https://gist.github.com/Dapid/512eb1f78ead1c5c2272f6586c2aa522

**Comment by Dapid** [comment] 2016-07-05 08:18
Github was convinced the issue was resolved, so it only let me answer closing the issue. Reopening.

**Comment by andreabedini** [comment] 2016-07-05 08:22
@Dapid the logs you attached likely show a different problem 

```
  tables/utilsextension.c:282:26: fatal error: blosc_filter.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
```

**Comment by tomkooij** [comment] 2016-07-05 08:30
@Dapid: I'm going to create a fresh `env` with pytables 3.2.2 installed and `pip install -U`. I did not check upgrading before release, but apparently we need to...

**Comment by dejlek** [comment] 2016-07-05 08:31
Guys, this needs to be fixed urgently... We all have this problem.

**Comment by andreabedini** [comment] 2016-07-05 08:33
@tomkooij you can reproduce also starting from a fresh venv, but it works if you `pip install .`. If you do `python setup.py sdist` and `pip install` the resulting tarball it doesn't work because of some files missing in `MANIFEST.in`. One is `cpuinfo.py` for sure. Now I am tracking down the blosc header.

**Comment by tomkooij** [comment] 2016-07-05 08:35
@andreabedini: Yes! Let's try to fix it and get a new tarball to pypi asap.

**Comment by andreabedini** [comment] 2016-07-05 08:39
@tomkooij please check fa021b1800763123a0d5b0d1cbf36a290d920321 just committed to master. Do the whole trip of making a sdist and installing the resulting tarball.

**Comment by tomkooij** [comment] 2016-07-05 08:41
buiding the tarball now.

**Comment by tomkooij** [comment] 2016-07-05 09:02
Build. And tested (on a different box). It seems to `pip install -U` now. I'm uploading to PyPI now.

I did not update the version. So, this means the release op PyPI does not match the tag pushed to github. I won't force push a tag right now, but think about it a little bit. Let's see if installs are fixed now.

**Comment by andreabedini** [comment] 2016-07-05 09:14
@tomkioij 🙌🏻 @dejlek @dapid please have another go

**Comment by tomkooij** [comment] 2016-07-05 09:15
Thank YOU @andreabedini 

I'm going to add a `pip install` and `pip install -U` check to the release procedure. This shouldn't happen.

**Comment by andreabedini** [comment] 2016-07-05 09:19
@tomkooij you did all the work for this release! We should change travis to try to install from the tarball rather than from the source dir.

**Comment by dejlek** [comment] 2016-07-05 09:30
`Successfully installed numexpr-2.6.0 numpy-1.11.1 tables-3.2.3.1` -- look OK guys! Thanks!

**Closed** 2016-07-05 09:52 UTC

**Comment by Dapid** [comment] 2016-07-05 10:51
It works for me too. Thanks!

**Comment by sbesson** [comment] 2016-07-05 10:57
Same here. Our daily deployment build which failed earlier this morning due to this issue now passed with `tables-3.2.3.1` installed. Thanks.
