### ISSUE TITLE
Wheels for macos arm64

### ISSUE THREAD

**Issue by maxnoe** [PyTables/PyTables#1157] opened 2024-04-16 07:22 UTC
Pytables currently only offers wheels on macos for 64 bit, it would be great if you could also provide wheels for arm64 (apple sillicon)

**Comment by avalentino** [comment] 2024-04-16 07:43
Dear @maxnoe 
there is currently an incomplete PR #1050 about this topic.
We managed to build wheels but, unfortunately, they seem not to be working due to the bundling of the incorrect version of the blosc2 library.
The origin of the issue is still not clear but any help is really welcome.

**Comment by cbrnr** [comment] 2024-04-16 11:34
The issue IIRC is that cibuildwheel uses the incorrect platform for installing. Building seems to work. It would be great if you commented/helped in #1050 @maxnoe!

**Comment by avalentino** [comment] 2024-04-16 21:37
Closing as duplicate of #832 and addressed by PR #1050.

**Closed by avalentino** 2024-04-16 21:37 UTC
