### ISSUE TITLE
Error when trying to fresh install tables 3.5.0

### ISSUE THREAD

**Issue by bdjellab** [PyTables/PyTables#725] opened 2019-03-13 16:59 UTC
OS: Linux
Distrib: Ubuntu 14.04 and 16.04

**Protocol**

In a virtualenv:
`pip install tables`

**Expected**

tables 3.5.0 is installed

**Observed**

```
Looking in links: http://10.0.2.107/pypi/
Collecting tables
/home/bdjellab/.virtualenvs/toto/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/bdjellab/.virtualenvs/toto/local/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/f9/cb/dfca7ec0f97d34bc9acd6e1658d5c5d3642dff5c453d65ee239eda82dcdd/tables-3.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/bin/ld : ne peut trouver -lhdf5
    collect2: error: ld returned 1 exit status
    * Using Python 2.7.6 (default, Oct 26 2016, 20:30:19)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zoQfEs/tables/

```

Installing version 3.4.4 still works fine but installing version 3.5.0 seems to be broken.

**Comment by FrancescAlted** [comment] 2019-03-13 18:13
This is because the wheels are not up yet (I am still waiting for the Travis CI to produce the wheels, so expect them to be up shortly).  Meanwhile, try installing the hdf5 package and the other dependencies in your Ubuntu box with:

```
# apt install libhdf5-dev python-numpy python-numexpr python-six python-mock
```

After that, you should be able to install the package.  For example, in my Ubuntu 16.04 box I am getting:

```
$ pip install tables -U
Collecting tables
  Downloading https://files.pythonhosted.org/packages/f9/cb/dfca7ec0f97d34bc9acd6e1658d5c5d3642dff5c453d65ee239eda82dcdd/tables-3.5.0.tar.gz (8.3MB)
    100% |████████████████████████████████| 8.3MB 14.6MB/s
Requirement already satisfied, skipping upgrade: numpy>=1.9.3 in ./miniconda3/lib/python3.6/site-packages (from tables) (1.15.4)
Requirement already satisfied, skipping upgrade: numexpr>=2.6.2 in ./miniconda3/lib/python3.6/site-packages (from tables) (2.6.4)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in ./miniconda3/lib/python3.6/site-packages (from tables) (1.12.0)
Requirement already satisfied, skipping upgrade: mock>=2.0 in ./miniconda3/lib/python3.6/site-packages (from tables) (2.0.0)
Requirement already satisfied, skipping upgrade: pbr>=0.11 in ./miniconda3/lib/python3.6/site-packages (from mock>=2.0->tables) (3.0.0)
Building wheels for collected packages: tables
  Building wheel for tables (setup.py) ... done
  Stored in directory: /home/francesc/.cache/pip/wheels/37/47/97/4696fc43368aa8e3956be2a36e399c9de2b8872ec83c713906
Successfully built tables
Installing collected packages: tables
  Found existing installation: tables 3.4.4
    Uninstalling tables-3.4.4:
      Successfully uninstalled tables-3.4.4
Successfully installed tables-3.5.0
```

**Comment by rigogsilva** [comment] 2019-03-13 21:50
@FrancescAlted thoughts on when the wheels will be produced? Appreciate it. I tried the apt installs but that did not work.

**Comment by zsluedem** [comment] 2019-03-14 07:40
```
https://files.pythonhosted.org/packages/34/07/aab004e53d06ec7fd38c3ecb695162b33fefbdd5abb7edf66b88eef8081a/tables-3.5.0-1.tar.gz (8.3MB)
    Complete output from command python setup.py egg_info:
    H5closenih0h_a6.c
    C:\Users\appveyor\AppData\Local\Temp\1\H5closenih0h_a6.c(2): warning C4013: 'H5close' undefined; assuming extern returning int
    LINK : fatal error LNK1181: cannot open input file 'hdf5.lib'
    * Using Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-install-9ztwhf0f\tables\
```

Same problem in windows system

**Comment by FrancescAlted** [comment] 2019-03-14 07:58
@rigogsilva I am on it.

@zsluedem This is curious because the windows wheels are up, and I tested the Python 3.7 + Win10 64-bit yesterday without problems.  Which are your Python and Win versions?

**Comment by zsluedem** [comment] 2019-03-14 08:01
@FrancescAlted 
Both Python3.6 and Python3.7 failed in my ci test.
You can see here https://ci.appveyor.com/project/zsluedem/monktrader/builds/23063880

**Comment by JanVargovsky** [comment] 2019-03-14 10:48
Same problem, Windows 10, Python 3.6.8.

```
Using cached https://files.pythonhosted.org/packages/34/07/aab004e53d06ec7fd38c3ecb695162b33fefbdd5abb7edf66b88eef8081a/tables-3.5.0-1.tar.gz
    Complete output from command python setup.py egg_info:
    H5closev1zkionk.c
    C:\Users\j.vargovsky\AppData\Local\Temp\H5closev1zkionk.c(2): warning C4013: 'H5close' undefined; assuming extern returning int
    LINK : fatal error LNK1181: cannot open input file 'hdf5.lib'
    * Using Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
    * USE_PKGCONFIG: False
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-3am57b5z\tables\
```

**Comment by FrancescAlted** [comment] 2019-03-14 11:46
I have uploaded the complete set of wheels files for Win, for Linux and for Mac (Python 3.4 wheels are not there becuase it is going to be unmaintained very soon).  However, an existing issue is that installing by the package name alone tries to download the sources (and compile the beast):

```
$ pip install tables
Collecting tables
  Downloading https://files.pythonhosted.org/packages/34/07/aab004e53d06ec7fd38c3ecb695162b33fefbdd5abb7edf66b88eef8081a/tables-3.5.0-1.tar.gz (8.3MB)
```

but if a version is specified, it works as intended:

```
$ pip install tables==3.5.0
Collecting tables==3.5.0
  Downloading https://files.pythonhosted.org/packages/00/58/19d121590c554012bff11a120743f1e2f066b7b568c3ce3d718716664ee4/tables-3.5.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (4.3MB)
```

Not sure what's going on.  Somebody can provide a hint?

**Comment by rigogsilva** [comment] 2019-03-14 13:32
`pip3 install tables` works for me now on a mac. Without the version.

**Comment by FrancescAlted** [comment] 2019-03-14 13:37
I think the root of the issue was that I uploaded a `tables-3.5.0-1.tar.gz` in the believe that the `-1` would represent the same than a [build tag](https://github.com/MacPython/wiki/wiki/Build-Tags), but I suspect that, when applied to a source tarball, it rather refers to a `-post1` version, and this is why the `-post1` wheels were not found unless the version was explicitly mentioned (e.g. `tables=3.5.0`).

With that, the easiest solution (the only one?) was to do a new release.  So tables 3.5.1 is out, and now wheels seem to be found correctly now.  For example:

```
(base) faltet@ubuntu:~$ pip install tables
Collecting tables
  Using cached https://files.pythonhosted.org/packages/f8/9c/c3effbef260b5d2dee65976db6fa5c68b4c13672d4033fc04744f038a64a/tables-3.5.1-cp37-cp37m-manylinux1_x86_64.whl
Requirement already satisfied: numexpr>=2.6.2 in ./miniconda3/lib/python3.7/site-packages (from tables) (2.6.9)
Requirement already satisfied: six>=1.9.0 in ./miniconda3/lib/python3.7/site-packages (from tables) (1.12.0)
Requirement already satisfied: numpy>=1.9.3 in ./miniconda3/lib/python3.7/site-packages (from tables) (1.15.4)
Requirement already satisfied: mock>=2.0 in ./miniconda3/lib/python3.7/site-packages (from tables) (2.0.0)
Requirement already satisfied: pbr>=0.11 in ./miniconda3/lib/python3.7/site-packages (from mock>=2.0->tables) (5.1.3)
Installing collected packages: tables
Successfully installed tables-3.5.1
```

I am going to close this, but feel free to complain in case 3.5.1 wheels do not work for you.

**Closed by FrancescAlted** 2019-03-14 13:37 UTC

**Comment by rigogsilva** [comment] 2019-03-14 13:59
Thanks @FrancescAlted!
